[package]
name = "pdfrum-raster-vello-cpu"
description = "vello_cpu implementation of pdfrum-render's RenderDevice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["pdf", "render", "vello", "rasterizer"]
categories = ["graphics", "rendering"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
pdfrum-render.workspace = true
pdfrum-page.workspace = true
kurbo.workspace = true
peniko.workspace = true
vello_cpu.workspace = true
