//! The exit check: does a page we *rewrote* draw what another
//! implementation says it draws?
//!
//! # Why this needs the oracle rather than a golden
//!
//! Every other pixel comparison in this harness diffs our render against a
//! golden the oracle produced from the *original* file. That cannot answer the
//! question page mutation raises, because the file being rendered here is one
//! neither implementation has ever seen: pdfrum edits a page, regenerates its
//! content stream and writes a new document, and the question is whether the
//! bytes it wrote mean the same thing to somebody else's reader.
//!
//! So the comparison is between two renders of *the same mutated file*: the
//! oracle's and ours. A regenerated stream that our own interpreter happens to
//! read back correctly, but that PDFium reads differently, fails here and
//! passes everywhere else — which is exactly the class of bug this sweep
//! exists to catch.
//!
//! # Three mutations, and what each one would fail on
//!
//! The tool's `--mutate=` applies one of three (see its `mutate` module).
//! Their failure modes are deliberately different:
//!
//! - **`add-rect`** would fail if the new `/Contents` element were not
//!   reachable — a `/Contents` that stayed a lone stream, an array whose
//!   entry pointed at nothing, a stream written with a `/Filter` it does not
//!   have. Its rectangle is half the page, so a reader that missed it loses
//!   a quarter of the pixels and no threshold hides that.
//! - **`remove-first`** would fail if removal bookkeeping were wrong: an
//!   element deleted that should have survived, an index left pointing past
//!   the end of a shrunken array, a resource swept away that the surviving
//!   objects still name.
//! - **`touch-all`** would fail on the emitter itself. It changes nothing, so
//!   the page it produces is meant to be the page it started from — minus the
//!   documented losses. It is the one that measures fidelity rather than
//!   plumbing.
//!
//! # The floor is 0.99, and it is a *cross-implementation* floor
//!
//! Two renderers never agree to the byte, so the score is SSIM rather than
//! equality; 0.99 is the same floor the Tier-B clusters use for a page that
//! renders correctly with sub-pixel differences. A regenerated page's
//! *content* losses do not enter into it, because both sides are reading the
//! same regenerated bytes — whatever the emitter dropped, it dropped for both.
//!
//! # A standing disagreement is not a mutation bug, and SSIM cannot say so
//!
//! Some files the two implementations already render differently, for reasons
//! nothing here can fix — an upstream JBIG2 decode gap, say. A mutation of
//! such a file inherits the disagreement without having caused any of it, and
//! must not be scored as though it had.
//!
//! SSIM alone cannot make that distinction, and the reason is worth stating
//! because it looks like a bug in the sweep. SSIM is a *local* metric: the
//! same handful of wrong pixels costs almost nothing inside a busy 8x8 window
//! and a great deal inside a flat one. `add-rect` paints a large flat
//! rectangle, so it turns busy windows into flat ones — and a file whose 76
//! wrong pixels scored 1.000 unmutated scores 0.986 mutated **without a
//! single new pixel having gone wrong**. Comparing the two SSIM numbers would
//! read that as a regression.
//!
//! So the baseline pass counts *pixels* instead. It renders a file with both
//! implementations and asks whether they disagreed at all. If they did, a
//! shortfall on the mutated file is attributed to the standing disagreement;
//! if they agreed exactly, the shortfall is the mutation's and the pair fails.
//! Both numbers are reported either way.
//!
//! # The baseline is a *plain save*, not the original
//!
//! One more subtlety, and it cost a wrong diagnosis to find. The baseline
//! cannot be the input file, because saving changes some files even with
//! nothing edited: the writer corrects a `/Length` that lied, so a stream the
//! original hid behind `/Length 0` comes back with its real payload and the
//! oracle then draws it. That is the *writer's* behaviour, identical under
//! `--save` and under `--mutate=`, and blaming a mutation for it would send
//! somebody hunting through the regenerator for a bug that is not there.
//!
//! So the baseline saves the file with no mutation at all and compares the two
//! implementations' renders of *that*. What is left is exactly the mutation's
//! contribution, which is the only thing this sweep is entitled to judge.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::corpus::Entry;
use crate::oracle::{OraclePaths, Pass, determinism_args};
use crate::run::ToolPaths;
use crate::saveroundtrip::{password_for, rate};
use crate::ssim;

/// The SSIM two renders of one mutated file must reach.
pub const FLOOR: f64 = 0.99;

/// The mutations the sweep applies, by the name `--mutate=` takes.
pub const MUTATIONS: [&str; 3] = ["add-rect", "remove-first", "touch-all"];

/// What one (file, mutation) pair found.
///
/// The four flags are four independent observations about one run, not a state
/// machine: a pair can save without mutating, mutate without reopening, or
/// reopen and fall short. Collapsing them into an enum would lose exactly the
/// combinations the sweep exists to count.
#[allow(
    clippy::struct_excessive_bools,
    reason = "four independent observations; see above"
)]
#[derive(Debug, Clone, PartialEq)]
pub struct MutationOutcome {
    /// The corpus-relative id.
    pub path: String,
    /// Which mutation was applied.
    pub mutation: String,
    /// Whether the tool wrote a mutated file at all.
    pub saved: bool,
    /// Whether the tool reported actually rewriting a content stream. A file
    /// whose page 0 draws nothing has nothing to mutate, and saying so is not
    /// a failure.
    pub mutated: bool,
    /// Whether the **oracle** reopened and rendered what we wrote.
    pub oracle_reopened: bool,
    /// The worst per-page SSIM between the oracle's render and ours, of the
    /// **mutated** file.
    pub ssim: Option<f64>,
    /// How many pixels the two implementations disagreed on for a **plain
    /// save** of the same file — the same document written by the same writer
    /// with nothing edited. `Some(0)` means they agreed exactly; `None` means
    /// the baseline was not measured, because the mutated file held the floor
    /// and there was nothing to explain.
    pub baseline_pixels: Option<u64>,
    /// How many pages were compared.
    pub pages: usize,
    /// Whether every compared page reached [`FLOOR`].
    pub within_floor: bool,
    /// Whether the shortfall is explained by a disagreement that predates the
    /// mutation — the two implementations do not render a plain save of this
    /// file identically either, so the edit is not what put the score below
    /// the floor.
    pub holds_baseline: bool,
    /// Why this file was skipped or fell short, when it did.
    pub note: String,
}

impl MutationOutcome {
    fn skipped(path: String, mutation: &str, why: String) -> Self {
        Self {
            path,
            mutation: mutation.to_owned(),
            saved: false,
            mutated: false,
            oracle_reopened: false,
            ssim: None,
            baseline_pixels: None,
            pages: 0,
            within_floor: true,
            holds_baseline: true,
            note: why,
        }
    }

    /// Whether this pair counts as a pass.
    ///
    /// A file with nothing to mutate passes trivially. Otherwise the oracle
    /// must have reopened what we wrote, and the mutated file must either
    /// reach the floor outright or fall short only on a page the two
    /// implementations already disagreed about — which keeps a standing
    /// decode gap from reading as a mutation bug.
    #[must_use]
    pub fn passed(&self) -> bool {
        if !self.mutated {
            return true;
        }
        self.oracle_reopened && (self.within_floor || self.holds_baseline)
    }
}

/// Run every mutation over one corpus entry.
pub fn check_one(
    entry: &Entry,
    tool: &ToolPaths,
    oracle: &OraclePaths,
    scratch: &Path,
    fixup: &Path,
) -> Vec<MutationOutcome> {
    let outcomes = MUTATIONS
        .iter()
        .map(|mutation| {
            let dir = scratch.join(mutation);
            let outcome = check_inner(entry, tool, oracle, mutation, &dir, fixup);
            std::fs::remove_dir_all(&dir).ok();
            outcome
        })
        .collect();
    std::fs::remove_dir_all(scratch).ok();
    outcomes
}

fn check_inner(
    entry: &Entry,
    tool: &ToolPaths,
    oracle: &OraclePaths,
    mutation: &str,
    scratch: &Path,
    fixup: &Path,
) -> MutationOutcome {
    let id = entry.id.clone();
    let password = password_for(&id);
    if std::fs::create_dir_all(scratch).is_err() {
        return MutationOutcome::skipped(id, mutation, "no scratch directory".to_owned());
    }
    let Ok(bytes) = crate::generate::materialize_for_run(entry, scratch, fixup) else {
        return MutationOutcome::skipped(id, mutation, "could not materialize".to_owned());
    };
    let input = scratch.join("input.pdf");
    if std::fs::write(&input, &bytes).is_err() {
        return MutationOutcome::skipped(id, mutation, "could not write the input".to_owned());
    }

    // ---- step 1: pdfrum mutates page 0 and saves ----
    let saved = scratch.join("input.pdf.saved.pdf");
    let Ok(run) = Command::new(&tool.binary)
        .args(determinism_args(&tool.font_dir))
        .args(password_arg(password))
        .arg(format!("--mutate={mutation}"))
        .arg(&input)
        .output()
    else {
        return MutationOutcome::skipped(id, mutation, "the tool would not run".to_owned());
    };
    if run.status.code().is_none() {
        return MutationOutcome::skipped(id, mutation, "the tool crashed".to_owned());
    }
    if !saved.exists() {
        return MutationOutcome::skipped(id, mutation, "the tool wrote no file".to_owned());
    }

    let stderr = String::from_utf8_lossy(&run.stderr);
    let mutated = stderr.contains("Mutated page 0");
    let mut outcome = MutationOutcome {
        path: id,
        mutation: mutation.to_owned(),
        saved: true,
        mutated,
        oracle_reopened: false,
        ssim: None,
        baseline_pixels: None,
        pages: 0,
        within_floor: true,
        holds_baseline: true,
        note: String::new(),
    };
    if !mutated {
        // "did nothing" is the tool's own line, and carrying its reason
        // through is what keeps this from reading as a silent pass.
        stderr
            .lines()
            .find(|line| line.starts_with("Mutation "))
            .unwrap_or("the tool did not report a mutation")
            .clone_into(&mut outcome.note);
        return outcome;
    }

    // ---- step 2: both implementations render the mutated file ----
    //
    // Into separate directories, because each renderer writes
    // `<name>.<page>.png` beside its input and the two would otherwise
    // overwrite each other.
    let Some(theirs) = render(
        &oracle.binary,
        &oracle.font_dir,
        &saved,
        password,
        scratch,
        "oracle",
    ) else {
        "the oracle could not reopen the mutated file".clone_into(&mut outcome.note);
        return outcome;
    };
    outcome.oracle_reopened = true;
    let Some(ours) = render(
        &tool.binary,
        &tool.font_dir,
        &saved,
        password,
        scratch,
        "ours",
    ) else {
        "we could not re-render our own mutated file".clone_into(&mut outcome.note);
        return outcome;
    };

    // ---- step 3: compare, page by page ----
    compare(&mut outcome, &theirs, &ours);

    // ---- step 4: the same comparison on the file nobody edited ----
    //
    // Only when the mutated file fell short, because the baseline costs two
    // more renders and its only job is to say whether the shortfall was
    // already there.
    if !outcome.within_floor && outcome.ssim.is_some() {
        let pixels = baseline(&tool_and_oracle(tool, oracle), &input, password, scratch);
        outcome.baseline_pixels = pixels;
        outcome.holds_baseline = pixels.is_some_and(|count| count > 0);
        let worst = outcome.ssim.unwrap_or_default();
        outcome.note = match pixels {
            Some(count) if count > 0 => format!(
                "ssim {worst:.6} below the {FLOOR:.2} floor, but the two \
                 implementations already disagree on {count} pixel(s) of a \
                 plain save of this file"
            ),
            Some(_) => format!(
                "ssim {worst:.6} below the {FLOOR:.2} floor; a plain save of \
                 this file renders identically in both, so the mutation lost \
                 this"
            ),
            None => format!("ssim {worst:.6} below the {FLOOR:.2} floor (no baseline)"),
        };
    }
    outcome
}

/// The two binaries, paired so the baseline pass takes one argument.
struct Both<'a> {
    tool: &'a ToolPaths,
    oracle: &'a OraclePaths,
}

fn tool_and_oracle<'a>(tool: &'a ToolPaths, oracle: &'a OraclePaths) -> Both<'a> {
    Both { tool, oracle }
}

/// How many pixels the two implementations disagree on for the **unmutated**
/// input, summed over its pages.
///
/// A count rather than a score, because the question is only *whether* they
/// already disagreed — see the module docs on why comparing two SSIM numbers
/// across a mutation cannot answer that.
fn baseline(both: &Both<'_>, input: &Path, password: Option<&str>, scratch: &Path) -> Option<u64> {
    // The subject is a plain save, not the input — see the module docs.
    let plain = plain_save(both.tool, input, password, scratch)?;
    let input = plain.as_path();
    let theirs = render(
        &both.oracle.binary,
        &both.oracle.font_dir,
        input,
        password,
        scratch,
        "base-oracle",
    )?;
    let ours = render(
        &both.tool.binary,
        &both.tool.font_dir,
        input,
        password,
        scratch,
        "base-ours",
    )?;
    let mut differing = 0u64;
    for (name, bytes) in &theirs {
        let (_, mine) = ours.iter().find(|(n, _)| n == name)?;
        let (Ok(a), Ok(b)) = (crate::pixels::decode(bytes), crate::pixels::decode(mine)) else {
            return None;
        };
        if a.width != b.width || a.height != b.height {
            // A size disagreement is a disagreement, and a large one.
            return Some(u64::from(a.width) * u64::from(a.height));
        }
        let count = a
            .rgba
            .as_chunks::<4>()
            .0
            .iter()
            .zip(b.rgba.as_chunks::<4>().0)
            .filter(|(x, y)| x != y)
            .count();
        differing = differing.saturating_add(u64::try_from(count).unwrap_or(u64::MAX));
    }
    Some(differing)
}

/// Save `input` with no mutation, and hand back where the tool wrote it.
///
/// The baseline's subject: the same document through the same writer, so what
/// is left over when it is subtracted is the mutation alone.
fn plain_save(
    tool: &ToolPaths,
    input: &Path,
    password: Option<&str>,
    scratch: &Path,
) -> Option<PathBuf> {
    let dir = scratch.join("plain");
    std::fs::create_dir_all(&dir).ok()?;
    let copy = dir.join("plain.pdf");
    std::fs::copy(input, &copy).ok()?;

    let out = Command::new(&tool.binary)
        .args(determinism_args(&tool.font_dir))
        .args(password_arg(password))
        .arg("--save")
        .arg(&copy)
        .output()
        .ok()?;
    out.status.code()?;
    let saved = dir.join("plain.pdf.saved.pdf");
    saved.exists().then_some(saved)
}

/// Render `file` with `binary` into its own copy of the file, so the two
/// renderers' artifacts do not collide.
fn render(
    binary: &Path,
    font_dir: &Path,
    file: &Path,
    password: Option<&str>,
    scratch: &Path,
    who: &str,
) -> Option<Vec<(String, Vec<u8>)>> {
    let dir = scratch.join(who);
    std::fs::create_dir_all(&dir).ok()?;
    let copy = dir.join("mutated.pdf");
    std::fs::copy(file, &copy).ok()?;

    let out = Command::new(binary)
        .args(determinism_args(font_dir))
        .args(password_arg(password))
        .args(Pass::Render.flags())
        .arg(&copy)
        .output()
        .ok()?;
    out.status.code()?;
    let stderr = String::from_utf8_lossy(&out.stderr);
    if stderr.contains("Load pdf docs unsuccessful") {
        return None;
    }
    let artifacts = crate::generate::harvest_for_run(&copy, Pass::Render).ok()?;
    // A render that produced no pages is not a render.
    (!artifacts.is_empty()).then_some(artifacts)
}

/// Fill in the SSIM fields from two renders of the same file.
fn compare(
    outcome: &mut MutationOutcome,
    theirs: &[(String, Vec<u8>)],
    ours: &[(String, Vec<u8>)],
) {
    let mut worst: Option<f64> = None;
    for (name, bytes) in theirs {
        let Some((_, mine)) = ours.iter().find(|(n, _)| n == name) else {
            outcome.within_floor = false;
            outcome.note = format!("we produced no {name}");
            return;
        };
        let (Ok(a), Ok(b)) = (crate::pixels::decode(bytes), crate::pixels::decode(mine)) else {
            outcome.within_floor = false;
            outcome.note = format!("{name} would not decode");
            return;
        };
        match ssim::compare(&a, &b) {
            Ok(diff) => {
                outcome.pages += 1;
                worst = Some(worst.map_or(diff.ssim, |w: f64| w.min(diff.ssim)));
            }
            Err(err) => {
                outcome.within_floor = false;
                outcome.note = format!("{name}: {err}");
                return;
            }
        }
    }
    outcome.ssim = worst;
    if let Some(worst) = worst
        && worst < FLOOR
    {
        outcome.within_floor = false;
        outcome.note = format!("ssim {worst:.6} below the {FLOOR:.2} floor");
    }
}

/// The `--password=` argument, as a zero- or one-element list.
fn password_arg(password: Option<&str>) -> Vec<String> {
    password
        .map(|p| format!("--password={p}"))
        .into_iter()
        .collect()
}

/// The tally over a whole sweep.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MutationTally {
    /// Pairs where a mutation was actually applied and saved.
    pub mutated: u64,
    /// Of those, how many the oracle reopened.
    pub reopened: u64,
    /// Of those, how many held the floor.
    pub within_floor: u64,
    /// Of those, how many fell short only on a page the two implementations
    /// already disagreed about before the edit.
    pub baseline_explained: u64,
    /// Pairs where there was nothing to mutate.
    pub nothing_to_do: u64,
    /// Pairs that never got as far as a save.
    pub skipped: u64,
    /// The worst SSIM seen anywhere.
    pub worst_ssim: Option<f64>,
}

impl MutationTally {
    /// Fold one outcome in.
    pub fn add(&mut self, outcome: &MutationOutcome) {
        if !outcome.saved {
            self.skipped += 1;
            return;
        }
        if !outcome.mutated {
            self.nothing_to_do += 1;
            return;
        }
        self.mutated += 1;
        if outcome.oracle_reopened {
            self.reopened += 1;
        }
        if outcome.oracle_reopened {
            if outcome.within_floor {
                self.within_floor += 1;
            } else if outcome.holds_baseline {
                self.baseline_explained += 1;
            }
        }
        if let Some(ssim) = outcome.ssim {
            self.worst_ssim = Some(self.worst_ssim.map_or(ssim, |w: f64| w.min(ssim)));
        }
    }

    /// The fraction of applied mutations the oracle reopened.
    #[must_use]
    pub fn reopen_rate(&self) -> Option<f64> {
        rate(self.reopened, self.mutated)
    }

    /// The fraction of applied mutations that held the floor.
    #[must_use]
    pub fn agreement_rate(&self) -> Option<f64> {
        rate(self.within_floor, self.mutated)
    }

    /// The fraction that either held the floor or fell short only on a page
    /// the two implementations already disagreed about. This is number.
    #[must_use]
    pub fn no_loss_rate(&self) -> Option<f64> {
        rate(
            self.within_floor.saturating_add(self.baseline_explained),
            self.mutated,
        )
    }
}

/// Where a sweep's per-file scratch lives.
#[must_use]
pub fn scratch_for(root: &Path, index: usize) -> PathBuf {
    root.join(format!("mutate-{index}"))
}

#[cfg(test)]
mod tests {
    use super::{FLOOR, MUTATIONS, MutationOutcome, MutationTally};

    fn outcome(mutated: bool, reopened: bool, ssim: Option<f64>) -> MutationOutcome {
        MutationOutcome {
            path: "f.pdf".to_owned(),
            mutation: "add-rect".to_owned(),
            saved: true,
            mutated,
            oracle_reopened: reopened,
            ssim,
            baseline_pixels: None,
            pages: 1,
            within_floor: ssim.is_none_or(|s| s >= FLOOR),
            // The default is the strict one: a shortfall is a failure unless a
            // baseline pass says the two implementations already disagreed.
            holds_baseline: ssim.is_none_or(|s| s >= FLOOR),
            note: String::new(),
        }
    }

    // The floor is the one the Tier-B clusters use for a correct render with
    // sub-pixel differences, and it is stated once.
    #[test]
    fn the_floor_is_the_documented_one() {
        assert!((FLOOR - 0.99).abs() < 1e-12);
    }

    #[test]
    fn the_three_mutations_are_the_ones_the_tool_offers() {
        assert_eq!(MUTATIONS, ["add-rect", "remove-first", "touch-all"]);
    }

    // A file with nothing to mutate is not a failure: the sweep runs over the
    // whole corpus, and plenty of it is pages that draw nothing.
    #[test]
    fn nothing_to_mutate_passes_and_is_counted_separately() {
        let outcome = outcome(false, false, None);
        assert!(outcome.passed());
        let mut tally = MutationTally::default();
        tally.add(&outcome);
        assert_eq!(tally.nothing_to_do, 1);
        assert_eq!(tally.mutated, 0);
        assert_eq!(tally.agreement_rate(), None);
    }

    // A mutation the oracle cannot reopen is the sharpest failure there is:
    // we wrote something only we can read.
    #[test]
    fn a_file_the_oracle_cannot_reopen_fails() {
        let outcome = outcome(true, false, None);
        assert!(!outcome.passed());
        let mut tally = MutationTally::default();
        tally.add(&outcome);
        assert_eq!(tally.mutated, 1);
        assert_eq!(tally.reopened, 0);
        assert_eq!(tally.reopen_rate(), Some(0.0));
    }

    #[test]
    fn a_score_below_the_floor_fails() {
        let outcome = outcome(true, true, Some(0.95));
        assert!(!outcome.passed());
        assert!(!outcome.within_floor);
    }

    // Unless the two implementations already disagreed about the unmutated
    // page, in which case the edit did not cause it.
    #[test]
    fn a_shortfall_on_a_page_they_already_disagreed_about_passes() {
        let mut outcome = outcome(true, true, Some(0.95));
        outcome.baseline_pixels = Some(76);
        outcome.holds_baseline = true;
        assert!(outcome.passed());

        let mut tally = MutationTally::default();
        tally.add(&outcome);
        assert_eq!(tally.baseline_explained, 1);
        assert_eq!(tally.within_floor, 0);
        assert_eq!(tally.no_loss_rate(), Some(1.0));
        // The absolute number stays honest.
        assert_eq!(tally.agreement_rate(), Some(0.0));
    }

    // A pixel-perfect unmutated baseline does not excuse anything: if the two
    // agree exactly before the edit and disagree after, the edit did it.
    #[test]
    fn a_shortfall_on_a_page_they_agreed_about_still_fails() {
        let mut outcome = outcome(true, true, Some(0.95));
        outcome.baseline_pixels = Some(0);
        outcome.holds_baseline = false;
        assert!(!outcome.passed());
    }

    // One differing pixel is a standing disagreement; zero is not. The line is
    // stated as a test because the whole point of counting pixels rather than
    // comparing scores is that this line is exact.
    #[test]
    fn one_differing_pixel_is_already_a_disagreement() {
        for (pixels, expected) in [(0u64, false), (1, true), (76, true)] {
            let mut outcome = outcome(true, true, Some(0.95));
            outcome.baseline_pixels = Some(pixels);
            outcome.holds_baseline = pixels > 0;
            assert_eq!(outcome.passed(), expected, "{pixels} pixels");
        }
    }

    #[test]
    fn a_score_at_the_floor_passes() {
        let outcome = outcome(true, true, Some(FLOOR));
        assert!(outcome.passed());
        let mut tally = MutationTally::default();
        tally.add(&outcome);
        assert_eq!(tally.agreement_rate(), Some(1.0));
        assert_eq!(tally.worst_ssim, Some(FLOOR));
    }

    // The tally keeps the worst score across everything, so one bad page is
    // visible in the summary rather than averaged away.
    #[test]
    fn the_tally_keeps_the_worst_score_it_saw() {
        let mut tally = MutationTally::default();
        tally.add(&outcome(true, true, Some(1.0)));
        tally.add(&outcome(true, true, Some(0.993)));
        tally.add(&outcome(true, true, Some(0.9999)));
        assert_eq!(tally.mutated, 3);
        assert_eq!(tally.within_floor, 3);
        assert!(tally.worst_ssim.is_some_and(|w| (w - 0.993).abs() < 1e-9));
    }
}
