//! Extracting every page's text. Ids `<class>/<stem>`.
//!
//! One `RenderSession` per iteration, reused across pages. Fresh each
//! iteration so the font parse is in the number. No oracle column.

use std::hint::black_box;
use std::time::Duration;

use criterion::{Criterion, criterion_main};
use pdfrum::{Document, RenderSession};
use pdfrum_corpus::{CORPUS, bytes};

/// Extracting every page's text.
fn text(c: &mut Criterion) {
    let mut group = c.benchmark_group("text");
    for doc in CORPUS {
        let Ok(opened) = Document::from_bytes(bytes(doc.stem)) else {
            continue;
        };
        group.bench_function(format!("{}/{}", doc.class.name(), doc.stem), |b| {
            b.iter(|| {
                let mut session = RenderSession::new();
                for page in opened.pages() {
                    black_box(page.text_on(&mut session).to_string().len());
                }
            });
        });
    }
    group.finish();
}

// `criterion_group!` generates a `pub fn` the `missing_docs` lint cannot see a
// doc comment for — the attribute would land inside the macro's expansion.
#[allow(missing_docs, reason = "the item is generated by criterion_group!")]
mod group {
    use super::{Criterion, Duration, text};
    use criterion::criterion_group;

    criterion_group! {
        name = benches;
        // measurement behind them.
        config = Criterion::default()
            .measurement_time(Duration::from_secs(5))
            .warm_up_time(Duration::from_secs(2))
            .sample_size(50);
        targets = text
    }
}

criterion_main!(group::benches);
