#!/usr/bin/env python3
"""Transcribe PDFium's Adobe CMYK->sRGB lookup table into Rust.

The table (`kCMYK` in `core/fxge/dib/cfx_cmyk_to_srgb.cpp`) is 9*9*9*9 = 6561
RGB triples sampling the Adobe CMYK rendering. It is data, not code: this
script reads the oracle header and emits `src/color/cmyk_table.rs`, and
`cmyk_table.rs`'s own test re-derives the shape so a transcription error
cannot pass CI.

Usage (from the workspace root, with the read-only oracle checked out):

    python3 crates/pdfrum-page/tools/gen_cmyk_table.py \
        /mnt/data2/pdfium/pdfium-c++/core/fxge/dib/cfx_cmyk_to_srgb.cpp \
        crates/pdfrum-page/src/color/cmyk_table.rs
"""

import re
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src, encoding="utf-8").read()
    start = text.index("kCMYK = {{")
    end = text.index("}};", start)
    body = text[start + len("kCMYK = {{") : end]
    triples = re.findall(r"\{\s*(\d+),\s*(\d+),\s*(\d+)\s*\}", body)
    if len(triples) != 6561:
        print(f"expected 6561 triples, found {len(triples)}", file=sys.stderr)
        return 1

    out = [
        "//! PDFium's Adobe CMYK-to-sRGB sample table, transcribed verbatim.",
        "//!",
        "//! 9x9x9x9 = 6561 RGB triples on a uniform CMYK grid, indexed",
        "//! `729*c + 81*m + 9*y + k` with each axis in `0..9`. Generated by",
        "//! `tools/gen_cmyk_table.py` from the oracle's",
        "//! `core/fxge/dib/cfx_cmyk_to_srgb.cpp`; the interpolation that reads",
        "//! it lives in `super::device`.",
        "",
        "/// Number of samples along each of the four CMYK axes.",
        "pub(crate) const AXIS: usize = 9;",
        "",
        "/// The sample grid. See the module docs for the index formula.",
        "pub(crate) static CMYK: [[u8; 3]; AXIS * AXIS * AXIS * AXIS] = [",
    ]
    for i in range(0, 6561, 4):
        row = "    " + " ".join(
            f"[{r}, {g}, {b}]," for (r, g, b) in triples[i : i + 4]
        )
        out.append(row)
    out.append("];")
    out.append("")
    open(dst, "w", encoding="utf-8").write("\n".join(out))
    print(f"wrote {dst} ({len(triples)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
