/* libpdfrum — the C ABI for the pdfrum PDF engine.
 *
 * GENERATED by cbindgen from crates/pdfrum-capi/src/. Do not edit by hand:
 * `scripts/capi-header.nu check` regenerates this file and fails CI on a
 * difference. Regenerate deliberately with `scripts/capi-header.nu update`.
 *
 * The contracts this header states — who owns which pointer, who frees what,
 * which handle may cross a thread — are written out per function below and in
 * docs/design/capi.md.
 *
 * NOT in this library: the facade's `javascript` feature. A document's own
 * scripts are never executed by libpdfrum, under any build — running untrusted
 * script out of a document is a different security proposition from rendering
 * one, and a C caller who wants it links the Rust facade with that feature
 * instead. There is no `pdfrum_script_*` and there is no runtime switch.
 *
 * Licensed under MIT OR Apache-2.0. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Why a call failed.
//
// One variant per [`pdfrum::ErrorCode`], with the same number, so the C enum
// and the Rust one cannot drift: its conversion from the facade is a total match and a
// new facade variant is a compile error here. The numbers are the facade's
// and are documented there; nothing in this library uses a magic integer for
// a failure kind.
enum pdfrum_code
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // No failure. Never stored in a filled `pdfrum_error`; it is the value a
    // zeroed one has, so a caller who forgot to check the return value still
    // reads a defined code.
    PDFRUM_CODE_OK = 0,
    // Reading or writing a file failed.
    PDFRUM_CODE_IO = 1,
    // The bytes are not a PDF, or are damaged past recovery.
    PDFRUM_CODE_OPEN = 2,
    // The document is encrypted and the password given does not open it.
    PDFRUM_CODE_WRONG_PASSWORD = 3,
    // An object could not be read from the file.
    PDFRUM_CODE_READ = 4,
    // Rendering the page failed.
    PDFRUM_CODE_RENDER = 5,
    // The document's structure is not what the operation needs.
    PDFRUM_CODE_DOC = 6,
    // Writing the document out failed.
    PDFRUM_CODE_SAVE = 7,
    // Text extraction failed.
    PDFRUM_CODE_TEXT = 8,
    // A limit in `pdfrum_limits` — pixels, time, or a parser bound — was
    // reached. A cancelled operation reports this code.
    PDFRUM_CODE_LIMIT = 9,
    // A pointer this library requires was null, an index was out of range, or
    // a string was not UTF-8. The caller's contract was not met; the library
    // answered rather than crashed.
    PDFRUM_CODE_ARGUMENT = 100,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum pdfrum_code pdfrum_code;
#else
typedef uint32_t pdfrum_code;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What kind of control a form field is.
//
// The number in `pdfrum_field::kind`. A total match over
// [`pdfrum::FieldKind`], which is not `#[non_exhaustive]`, so a kind added
// upstream is a compile error here rather than a silent renumbering — which
// is what a C caller switching on this number needs.
enum pdfrum_field_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    // A push button: it carries no value.
    PDFRUM_FIELD_KIND_BUTTON = 0,
    // A check box.
    PDFRUM_FIELD_KIND_CHECKBOX = 1,
    // One button of a radio group.
    PDFRUM_FIELD_KIND_RADIO = 2,
    // A single- or multi-line text field.
    PDFRUM_FIELD_KIND_TEXT = 3,
    // A drop-down list.
    PDFRUM_FIELD_KIND_COMBO = 4,
    // A scrolling list.
    PDFRUM_FIELD_KIND_LIST = 5,
    // A signature field.
    PDFRUM_FIELD_KIND_SIGNATURE = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum pdfrum_field_kind pdfrum_field_kind;
#else
typedef uint32_t pdfrum_field_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A document's embedded files.
//
// From `pdfrum_document_attachments`. Owns every string each entry carries;
// the *contents* of an attachment come separately, from
// `pdfrum_attachments_data`.
typedef struct pdfrum_attachments pdfrum_attachments;

// A document's outline, flattened depth-first.
//
// From `pdfrum_document_bookmarks`. Owns each entry's `title`.
typedef struct pdfrum_bookmarks pdfrum_bookmarks;

// A flag a host raises to stop work already in progress.
//
// A distinct newtype rather than a bare pointer to [`pdfrum::Deadline`], so
// the boundary's signatures say which handle each function takes.
//
// The handle is **thread-safe on purpose** — that is what it is for. A worker
// renders while another thread calls `pdfrum_cancel_stop`, and the render
// fails with `PDFRUM_CODE_LIMIT` at its next check. It is the one handle in
// this header that may be used from several threads at once.
typedef struct pdfrum_cancel pdfrum_cancel;

// An open PDF document.
//
// The root handle: pages, forms, bookmarks, attachments, metadata and images
// all come from one of these, and each keeps the document alive for as long
// as it lives, so closing the document while a page of it is open is defined
// — the bytes stay until the last handle goes.
//
// **Threads.** A document may be used from any thread and from several at
// once: every function that takes a `const pdfrum_document *` is safe to call
// concurrently. That is what makes the one-document-many-workers shape in
// `ctest/test.c` possible. [`pdfrum_close`] is the exception, as every free
// is: it needs the handle to itself.
typedef struct pdfrum_document pdfrum_document;

// A document's interactive form, and the values written into it so far.
//
// Holds a reference to its document, so the document may be closed while the
// form is still open.
//
// **Writes are buffered.** `pdfrum_form_set` and `pdfrum_form_set_checked`
// change nothing in the document; they record a value that
// [`pdfrum_form_save`] writes out. That is what lets one immutable document
// back several independent forms at once, and it is why filling a form never
// fails for want of a lock.
//
// **Threads.** A form is single-threaded, and the setters need it
// exclusively.
typedef struct pdfrum_form pdfrum_form;

// Every occurrence of a needle in a page's text.
//
// From `pdfrum_page_search`. Carries no strings; it is a handle anyway so the
// six lists have one shape a caller learns once.
typedef struct pdfrum_hits pdfrum_hits;

// The images drawn on one page.
//
// From `pdfrum_document_images`. The pixels come separately, from
// `pdfrum_images_pixels`.
typedef struct pdfrum_images pdfrum_images;

// Every link on a page.
//
// From `pdfrum_page_links`. Owns each link's `uri`.
typedef struct pdfrum_links pdfrum_links;

// One page of an open document.
//
// Holds a reference to its document, so the document may be closed while the
// page is still open.
//
// **Threads.** A page is single-threaded: use one from one thread at a time.
// The supported way to render in parallel is a page per worker, all taken
// from one shared `pdfrum_document`.
typedef struct pdfrum_page pdfrum_page;

// Every word on a page, in reading order.
//
// From `pdfrum_page_words`. Owns each word's `text` and `font`, which is why
// there is no per-word free.
typedef struct pdfrum_words pdfrum_words;

// A block of bytes the library allocated and the caller owns.
//
// Filled by every function that hands out bytes — `pdfrum_document_save`,
// `pdfrum_form_save`, `pdfrum_images_pixels`. Free `data` with
// [`pdfrum_free`] when done; `len` is the number of bytes and `data` is not
// NUL-terminated.
typedef struct {
    // The bytes, or null if the call that would have filled this failed.
    uint8_t *data;
    // How many bytes `data` points to.
    uintptr_t len;
} pdfrum_buffer;

// One file embedded in a document.
//
// The bytes are not in this struct: read them with
// [`pdfrum_attachments_data`], which allocates a buffer the caller frees.
typedef struct {
    // The name the document files this attachment under, owned by the handle.
    const char *name;
    // The attachment's own file name, owned by the handle.
    const char *file_name;
    // Its description, owned by the handle; empty when the document gives
    // none.
    const char *description;
    // Its MIME type, owned by the handle, or null when the document does not
    // say.
    const char *subtype;
} pdfrum_attachment;

// One entry of a document's outline.
typedef struct {
    // The entry's text, owned by the handle.
    const char *title;
    // How deep the entry sits: 0 for a top-level entry, 1 for its children,
    // and so on. The list is depth-first, so a run of deeper entries after
    // one is that one's subtree.
    uintptr_t depth;
    // The zero-based page the entry goes to, or `UINT32_MAX` when it does not
    // name a page of this document.
    uint32_t page_index;
} pdfrum_bookmark;

// A failed call's code and message.
//
// The caller allocates this — on its stack is the usual place — and passes
// its address as the trailing argument of a fallible function. On failure the
// library sets `code` and stores a heap-allocated, NUL-terminated UTF-8
// `message`; on success it touches neither field.
//
// `message` is owned by the caller once it is set and is freed by
// `pdfrum_error_free`, which is safe to call on a zeroed or already-freed
// error.
typedef struct {
    // Why the call failed. `PDFRUM_CODE_OK` in an error nothing has failed
    // into, so a caller who zeroed the struct reads a defined value.
    pdfrum_code code;
    // The message, or null when nothing failed.
    char *message;
} pdfrum_error;

// A document's information dictionary, as eight strings.
//
// Every field is a `char *` that is null when the document does not carry
// that entry. The whole struct is freed at once by [`pdfrum_metadata_free`];
// the individual strings must **not** be passed to `pdfrum_free`.
typedef struct {
    // `/Title`, or null.
    char *title;
    // `/Author`, or null.
    char *author;
    // `/Subject`, or null.
    char *subject;
    // `/Keywords`, or null.
    char *keywords;
    // `/Creator`, or null.
    char *creator;
    // `/Producer`, or null.
    char *producer;
    // `/CreationDate` as the PDF date string it is, or null.
    char *creation_date;
    // `/ModDate` as the PDF date string it is, or null.
    char *modification_date;
} pdfrum_metadata;

// How a save is written.
typedef struct {
    // Write the same bytes for the same input every time: no timestamps and a
    // file identifier derived from the content rather than the clock. What a
    // build system or a test wants.
    bool deterministic;
    // Drop the document's encryption, writing the result in the clear. The
    // caller is responsible for whether that is allowed; the library reports
    // the permissions and does not enforce them.
    bool remove_security;
} pdfrum_save_options;

// One field of a form.
typedef struct {
    // The field's fully-qualified name, owned by the form handle and invalid
    // once the form is freed.
    const char *name;
    // Its value, seen through every `pdfrum_form_set` made so far. Owned by
    // the form handle.
    const char *value;
    // What kind of control the field is.
    pdfrum_field_kind kind;
    // Whether a check box or radio button is currently selected. Always
    // `false` for a field of another kind.
    bool is_checked;
    // Whether the document marks this field as not editable.
    bool is_read_only;
    // Whether the document marks this field as one that must be filled.
    bool is_required;
} pdfrum_field;

// One occurrence of a search needle in a page's text.
typedef struct {
    // The first character of the match, as an index into `pdfrum_page_text`.
    uintptr_t start;
    // One past the last character.
    uintptr_t end;
} pdfrum_hit;

// One image drawn on a page.
//
// The pixels are not in this struct: read them with [`pdfrum_images_pixels`],
// which allocates a buffer the caller frees.
typedef struct {
    // The image's width in its own pixels, not as drawn on the page.
    uint32_t width;
    // Its height in its own pixels.
    uint32_t height;
    // Whether the image is a stencil mask rather than a picture: it paints
    // the current fill colour through a one-bit shape.
    bool is_mask;
} pdfrum_image;

// One link on a page.
typedef struct {
    // Left edge of the clickable area, in PDF points.
    double x0;
    // Bottom edge.
    double y0;
    // Right edge.
    double x1;
    // Top edge.
    double y1;
    // The URI this link opens, owned by the handle, or null when the link
    // goes to a page of this document instead.
    const char *uri;
    // The zero-based page this link goes to, or `UINT32_MAX` when it does not
    // go to a page of this document.
    uint32_t page_index;
} pdfrum_link;

// The limits and cancellation an open runs under.
//
// A struct rather than a positional list, so a field added later does not
// renumber a call. Zero means "no limit" for both numbers and a null
// `cancel` means "not cancellable", so a zeroed `pdfrum_limits` is exactly
// the default [`pdfrum_open`] uses.
typedef struct {
    // The largest render this document will attempt, in pixels. Zero leaves
    // the facade's own default in place.
    uint64_t max_render_pixels;
    // A flag from `pdfrum_cancel_new`, or null. Raising it stops work in
    // progress; the handle must outlive the document unless it is freed,
    // which is always allowed because the flag is reference-counted inside.
    pdfrum_cancel *cancel;
    // A wall-clock budget in milliseconds, counted from the open. Zero means
    // no budget.
    uint64_t time_limit_ms;
} pdfrum_limits;

// One word of a page's text.
//
// The rectangle is in PDF points in the page's own space, `y` growing upward
// from the bottom-left as PDF measures it — the same space
// `pdfrum_page_size` reports and *not* the top-down pixel space a render
// produces.
typedef struct {
    // Left edge.
    double x0;
    // Bottom edge.
    double y0;
    // Right edge.
    double x1;
    // Top edge.
    double y1;
    // The font size this word was set at, in points.
    double size;
    // The first character of the word, as an index into `pdfrum_page_text`.
    uintptr_t start;
    // One past the last character, so `end - start` is the length.
    uintptr_t end;
    // The word's text, owned by the handle.
    const char *text;
    // The font the word was set in, owned by the handle, or null when the
    // page does not say.
    const char *font;
} pdfrum_word;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// How many attachments the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_attachments` that has not been freed.
uintptr_t pdfrum_attachments_count(const pdfrum_attachments *list);

// The bytes of one attachment.
//
// Fills `out` with the file's contents; the caller frees `out->data` with
// `pdfrum_free`. Returns `false` — leaving `out` untouched — for a null
// handle, a null `out`, an index past the end, or an attachment whose stream
// the document does not actually carry.
//
// # Safety
//
// `list` is null or a live, unfreed attachments handle. `out` is null or
// points to a writable `pdfrum_buffer`.
bool pdfrum_attachments_data(const pdfrum_attachments *list,
                             uintptr_t index,
                             pdfrum_buffer *out);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_attachments` that has not already been freed, and no
// other thread is using it.
void pdfrum_attachments_free(pdfrum_attachments *list);

// Copies one of the attachments into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// Any `const char *` the item carries points **into the handle** and is
// invalid once the handle is freed. Copy it if it must outlive the list.
//
// # Safety
//
// `list` is null or a live `pdfrum_attachments` that has not been freed. `out` is null
// or points to a writable `pdfrum_attachment`.
bool pdfrum_attachments_get(const pdfrum_attachments *list,
                            uintptr_t index,
                            pdfrum_attachment *out);

// How many bookmarks the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_bookmarks` that has not been freed.
uintptr_t pdfrum_bookmarks_count(const pdfrum_bookmarks *list);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_bookmarks` that has not already been freed, and no
// other thread is using it.
void pdfrum_bookmarks_free(pdfrum_bookmarks *list);

// Copies one of the bookmarks into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// Any `const char *` the item carries points **into the handle** and is
// invalid once the handle is freed. Copy it if it must outlive the list.
//
// # Safety
//
// `list` is null or a live `pdfrum_bookmarks` that has not been freed. `out` is null
// or points to a writable `pdfrum_bookmark`.
bool pdfrum_bookmarks_get(const pdfrum_bookmarks *list,
                          uintptr_t index,
                          pdfrum_bookmark *out);

// Frees a cancellation flag.
//
// Safe to call while documents opened under the flag are still open: those
// hold their own reference to the shared flag, and freeing this handle only
// gives up C's. A null pointer is a no-op.
//
// # Safety
//
// `cancel` is null or a live handle from [`pdfrum_cancel_new`] that has not
// already been freed, and no other thread is using it.
void pdfrum_cancel_free(pdfrum_cancel *cancel);

// A new cancellation flag, unraised.
//
// The caller owns the returned handle and frees it with
// [`pdfrum_cancel_free`] — which is safe to call while a document opened with
// the flag is still alive, because the flag itself is reference-counted
// inside.
//
// Returns null only if the allocation fails.
pdfrum_cancel *pdfrum_cancel_new(void);

// Raises the flag.
//
// Every operation running under a `pdfrum_limits` that names this flag stops
// at its next check and fails with `PDFRUM_CODE_LIMIT`. The flag stays raised:
// there is no reset, and a host that wants to work again makes a new one.
//
// A null pointer is a no-op. This is the one function in the header that may
// be called concurrently with any other on the same handle — indeed it is
// meant to be called while another thread renders.
//
// # Safety
//
// `cancel` is null or a live handle from [`pdfrum_cancel_new`] that has not
// been freed.
void pdfrum_cancel_stop(const pdfrum_cancel *cancel);

// Closes a document.
//
// Every page, form and list handle taken from this document holds its own
// reference, so closing here while one is still open is defined: the
// document's bytes stay until the last of them is freed. A null pointer is a
// no-op.
//
// # Safety
//
// `document` is null or a live handle from an open that has not already been
// closed, and no other thread is using it.
void pdfrum_close(pdfrum_document *document);

// The document's embedded files, as a list handle.
//
// The caller frees the list with `pdfrum_attachments_free`.
//
// # Safety
//
// As [`pdfrum_document_bookmarks`].
pdfrum_attachments *pdfrum_document_attachments(const pdfrum_document *document,
                                                pdfrum_error *error);

// The document's outline, flattened depth-first into a list handle.
//
// The caller frees the list with `pdfrum_bookmarks_free`. A document with no
// outline yields an empty list, not a failure.
//
// # Safety
//
// `document` is null or a live, unclosed document handle. `error` is null or
// points to a writable `pdfrum_error`.
pdfrum_bookmarks *pdfrum_document_bookmarks(const pdfrum_document *document,
                                            pdfrum_error *error);

// The images drawn on one page, as a list handle.
//
// `page_index` is zero-based. The caller frees the list with
// `pdfrum_images_free`, and reads each image's pixels with
// `pdfrum_images_pixels`.
//
// # Safety
//
// As [`pdfrum_document_bookmarks`].
pdfrum_images *pdfrum_document_images(const pdfrum_document *document,
                                      uint32_t page_index,
                                      pdfrum_error *error);

// The document's information dictionary.
//
// Fills `out` with eight `char *`, each null where the document says nothing.
// The whole struct is freed by [`pdfrum_metadata_free`] and its strings must
// not be freed individually.
//
// Returns `false` on failure with `error` filled.
//
// # Safety
//
// `document` is null or a live, unclosed document handle. `out` is non-null
// and points to a writable `pdfrum_metadata`. `error` is null or points to a
// writable `pdfrum_error`.
bool pdfrum_document_metadata(const pdfrum_document *document,
                              pdfrum_metadata *out,
                              pdfrum_error *error);

// Writes the document out to a byte buffer the caller owns.
//
// `options` may be null, which is the same as a zeroed `pdfrum_save_options`.
// On success `out` is filled and the caller frees `out->data` with
// `pdfrum_free`; on failure `false` comes back and `out` is untouched.
//
// # Safety
//
// `document` is null or a live, unclosed document handle. `options` is null
// or points to a readable `pdfrum_save_options`. `out` is non-null and points
// to a writable `pdfrum_buffer`. `error` is null or points to a writable
// `pdfrum_error`.
bool pdfrum_document_save(const pdfrum_document *document,
                          const pdfrum_save_options *options,
                          pdfrum_buffer *out,
                          pdfrum_error *error);

// Frees the message a failed call stored in an error.
//
// Sets `message` back to null, so calling this twice on the same error is
// defined and does nothing the second time. A null `error`, or one whose
// `message` is already null, is a no-op — an error that no call ever failed
// into needs no cleanup, and a caller need not track which.
//
// # Safety
//
// `error` is null or points to a `pdfrum_error` this library filled, whose
// `message` has not already been freed by any means other than this function.
void pdfrum_error_free(pdfrum_error *error);

// Copies one field into `out`.
//
// `index` is zero-based, in the order the field tree reaches the fields.
// Returns `false` — leaving `out` untouched — for a null handle, a null
// `out`, or an index past the end.
//
// **`name` and `value` are borrowed from the form handle** and are invalidated
// by the next call on it, including the next `pdfrum_form_field`. A caller
// that keeps either past that copies it.
//
// # Safety
//
// `form` is null or a live, unfreed form handle, and the caller has it
// exclusively for the duration of the call. `out` is null or points to a
// writable `pdfrum_field`. `error` is null or points to a writable
// `pdfrum_error`.
bool pdfrum_form_field(pdfrum_form *form,
                       uintptr_t index,
                       pdfrum_field *out,
                       pdfrum_error *error);

// How many fields the form has.
//
// Returns 0 for a null handle.
//
// # Safety
//
// `form` is null or a live, unfreed form handle.
uintptr_t pdfrum_form_field_count(const pdfrum_form *form);

// Frees a form handle and every string it lent out.
//
// The document it came from stays open. A null pointer is a no-op.
//
// # Safety
//
// `form` is null or a live form handle that has not already been freed, and
// no other thread is using it.
void pdfrum_form_free(pdfrum_form *form);

// Opens a document's interactive form.
//
// Returns null when the document has no form — which is not a failure and
// fills no error — or for a null document. The caller frees the handle with
// [`pdfrum_form_free`]; the document may be closed first.
//
// # Safety
//
// `document` is null or a live, unclosed document handle.
pdfrum_form *pdfrum_form_open(const pdfrum_document *document);

// Writes the document out with the form's buffered values applied.
//
// `options` may be null, which is the same as a zeroed
// `pdfrum_save_options`. On success `out` is filled and the caller frees
// `out->data` with `pdfrum_free`.
//
// The form handle is unchanged: its buffered writes stay buffered, so a
// caller may save, write more, and save again.
//
// # Safety
//
// `form` is null or a live, unfreed form handle. `options` is null or points
// to a readable `pdfrum_save_options`. `out` is non-null and points to a
// writable `pdfrum_buffer`. `error` is null or points to a writable
// `pdfrum_error`.
bool pdfrum_form_save(const pdfrum_form *form,
                      const pdfrum_save_options *options,
                      pdfrum_buffer *out,
                      pdfrum_error *error);

// Writes a value into a field.
//
// The write is buffered: nothing in the document changes until
// [`pdfrum_form_save`]. For a check box or radio button `value` is the state
// name the widget's appearance dictionary lists, or `Off` to clear it;
// [`pdfrum_form_set_checked`] handles the common two-state case.
//
// Returns `false` on failure with `error` filled — in particular
// `PDFRUM_CODE_ARGUMENT` when no field has this name.
//
// # Safety
//
// `form` is null or a live, unfreed form handle held exclusively. `name` and
// `value` are non-null NUL-terminated UTF-8 strings. `error` is null or
// points to a writable `pdfrum_error`.
bool pdfrum_form_set(pdfrum_form *form,
                     const char *name,
                     const char *value,
                     pdfrum_error *error);

// Checks or clears a check box or radio button.
//
// `true` selects the field's first non-`Off` state, which for a check box is
// the only one it has. Buffered like [`pdfrum_form_set`].
//
// # Safety
//
// As [`pdfrum_form_set`], without a `value`.
bool pdfrum_form_set_checked(pdfrum_form *form,
                             const char *name,
                             bool checked,
                             pdfrum_error *error);

// Frees a string or a byte buffer the library handed out.
//
// The one free for every `char *` and every `pdfrum_buffer::data` in this
// header. It is **not** for handles — a `pdfrum_document *` is closed by
// `pdfrum_close`, a `pdfrum_page *` by `pdfrum_page_close`, and each list
// handle by its own `*_free` — and it is not for the static
// [`pdfrum_version`] string.
//
// A null pointer is a no-op, so a caller need not guard a pointer that a
// failed call left null.
//
// # Safety
//
// `ptr` is null, or is a `char *` or a `pdfrum_buffer::data` this library
// returned and that has not already been freed. Passing anything else —
// a handle, a pointer from `malloc`, an interior pointer — is undefined.
void pdfrum_free(void *ptr);

// How many hits the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_hits` that has not been freed.
uintptr_t pdfrum_hits_count(const pdfrum_hits *list);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_hits` that has not already been freed, and no
// other thread is using it.
void pdfrum_hits_free(pdfrum_hits *list);

// Copies one of the hits into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// The item is plain data: it borrows nothing from the handle.
//
// # Safety
//
// `list` is null or a live `pdfrum_hits` that has not been freed. `out` is null
// or points to a writable `pdfrum_hit`.
bool pdfrum_hits_get(const pdfrum_hits *list, uintptr_t index, pdfrum_hit *out);

// How many images the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_images` that has not been freed.
uintptr_t pdfrum_images_count(const pdfrum_images *list);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_images` that has not already been freed, and no
// other thread is using it.
void pdfrum_images_free(pdfrum_images *list);

// Copies one of the images into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// The item is plain data: it borrows nothing from the handle.
//
// # Safety
//
// `list` is null or a live `pdfrum_images` that has not been freed. `out` is null
// or points to a writable `pdfrum_image`.
bool pdfrum_images_get(const pdfrum_images *list,
                       uintptr_t index,
                       pdfrum_image *out);

// The pixels of one image, as RGBA8 straight alpha, row-major, top-down.
//
// The buffer is `width * height * 4` bytes for the `width` and `height`
// `pdfrum_images_get` reported for the same index. The caller frees
// `out->data` with `pdfrum_free`. Returns `false` — leaving `out` untouched —
// for a null handle, a null `out`, or an index past the end.
//
// # Safety
//
// `list` is null or a live, unfreed images handle. `out` is null or points to
// a writable `pdfrum_buffer`.
bool pdfrum_images_pixels(const pdfrum_images *list,
                          uintptr_t index,
                          pdfrum_buffer *out);

// How many links the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_links` that has not been freed.
uintptr_t pdfrum_links_count(const pdfrum_links *list);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_links` that has not already been freed, and no
// other thread is using it.
void pdfrum_links_free(pdfrum_links *list);

// Copies one of the links into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// Any `const char *` the item carries points **into the handle** and is
// invalid once the handle is freed. Copy it if it must outlive the list.
//
// # Safety
//
// `list` is null or a live `pdfrum_links` that has not been freed. `out` is null
// or points to a writable `pdfrum_link`.
bool pdfrum_links_get(const pdfrum_links *list,
                      uintptr_t index,
                      pdfrum_link *out);

// Frees every string in a metadata struct and zeroes it.
//
// Calling this twice is defined and does nothing the second time. A null
// pointer is a no-op.
//
// # Safety
//
// `metadata` is null or points to a `pdfrum_metadata` that
// [`pdfrum_document_metadata`] filled and that has not already been freed.
void pdfrum_metadata_free(pdfrum_metadata *metadata);

// Opens a document from bytes in memory.
//
// The bytes are **copied** into the library, so the caller's buffer may be
// freed or reused as soon as this returns. `password` may be null for a
// document that needs none; a wrong one fails with `PDFRUM_CODE_WRONG_PASSWORD`.
//
// Returns a handle the caller closes with [`pdfrum_close`], or null on
// failure with `error` filled.
//
// # Safety
//
// `bytes` points to at least `len` readable bytes. `password` is null or a
// NUL-terminated UTF-8 string. `error` is null or points to a writable
// `pdfrum_error`.
pdfrum_document *pdfrum_open(const uint8_t *bytes,
                             uintptr_t len,
                             const char *password,
                             pdfrum_error *error);

// Opens a document from a file.
//
// The library reads the file itself; `path` is a host path in the platform's
// own encoding, which on every platform this library builds for is UTF-8.
// `password` may be null.
//
// # Safety
//
// `path` is a non-null NUL-terminated string. `password` is null or a
// NUL-terminated UTF-8 string. `error` is null or points to a writable
// `pdfrum_error`.
pdfrum_document *pdfrum_open_file(const char *path,
                                  const char *password,
                                  pdfrum_error *error);

// [`pdfrum_open`] with limits and a cancellation flag.
//
// `limits` may be null, which is the same as a zeroed one and therefore the
// same as [`pdfrum_open`]. The limits govern the document for its whole life,
// not just the open: a render that exceeds `max_render_pixels`, or runs past
// `time_limit_ms`, or meets a raised `cancel`, fails with
// `PDFRUM_CODE_LIMIT`.
//
// # Safety
//
// As [`pdfrum_open`], and `limits` is null or points to a readable
// `pdfrum_limits` whose `cancel` is null or a live `pdfrum_cancel`.
pdfrum_document *pdfrum_open_with(const uint8_t *bytes,
                                  uintptr_t len,
                                  const char *password,
                                  const pdfrum_limits *limits,
                                  pdfrum_error *error);

// One page of the document, as a handle that keeps the document alive.
//
// `index` is zero-based; one past the end fails with `PDFRUM_CODE_DOC`.
//
// **Threads.** The returned page is single-threaded: use it from one thread
// at a time. Taking a page per worker from one shared document is the
// supported way to render in parallel, and is what `ctest/test.c` proves.
//
// The caller closes the page with [`pdfrum_page_close`].
//
// # Safety
//
// `document` is null or a live, unclosed document handle. `error` is null or
// points to a writable `pdfrum_error`.
pdfrum_page *pdfrum_page(const pdfrum_document *document,
                         uint32_t index,
                         pdfrum_error *error);

// Closes a page.
//
// The document it came from stays open; a page holds its own reference, so
// the order in which a caller closes a document and its pages does not
// matter. A null pointer is a no-op.
//
// # Safety
//
// `page` is null or a live page handle that has not already been closed, and
// no other thread is using it.
void pdfrum_page_close(pdfrum_page *page);

// How many pages the document has.
//
// Returns 0 for a null handle, which is also a legitimate answer for a
// document with no pages; a caller who must tell them apart checks the handle
// it was given.
//
// # Safety
//
// `document` is null or a live, unclosed document handle.
uint32_t pdfrum_page_count(const pdfrum_document *document);

// The page's links, as a list handle.
//
// The same no-per-item-free shape as [`pdfrum_page_words`]: free the lot with
// `pdfrum_links_free`, and every `const char *` a link carries dies with the
// handle.
//
// # Safety
//
// As [`pdfrum_page_words`].
pdfrum_links *pdfrum_page_links(const pdfrum_page *page, pdfrum_error *error);

#if defined(PDFRUM_MARKDOWN)
// The page as Markdown.
//
// Only present when the library was built with the `markdown` feature; a
// build without it does not export this symbol and the header says so.
//
// The caller owns the returned string and frees it with `pdfrum_free`.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `error` is null or points
// to a writable `pdfrum_error`.
char *pdfrum_page_markdown(const pdfrum_page *page, pdfrum_error *error);
#endif

// Renders the page into a buffer the caller owns.
//
// The caller queries [`pdfrum_page_render_size`] first and allocates at least
// `stride * height` bytes. The library writes **RGBA8, straight (not
// premultiplied) alpha, row-major, top-down**: pixel *(x, y)* begins at
// `rgba[y * stride + x * 4]` and is red, green, blue, alpha in that order.
//
// `stride` must be at least `width * 4`; a larger one lets a caller render
// into a padded or sub-rectangle-of-a-larger-image buffer. `width` and
// `height` may each be null; when given, they receive the size actually
// rendered, which is the size `pdfrum_page_render_size` reported.
//
// The buffer is the caller's throughout: the library never frees it and never
// keeps a pointer to it past the call. Returns `false` on failure with
// `error` filled, in which case the buffer's contents are unspecified.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `rgba` points to at least
// `stride * height` writable bytes, where `height` is what
// [`pdfrum_page_render_size`] reported for this `scale`. `width`, `height`
// and `error` are each null or writable.
bool pdfrum_page_render(const pdfrum_page *page,
                        double scale,
                        uint8_t *rgba,
                        uintptr_t stride,
                        uint32_t *width,
                        uint32_t *height,
                        pdfrum_error *error);

// The pixel size and buffer stride a render at `scale` needs.
//
// Call this first, allocate `stride * height` bytes, then call
// [`pdfrum_page_render`] with the same `scale`. The stride reported is the
// tightest one — `width * 4` — and a caller may pass a larger one to the
// render if its own buffer is padded.
//
// Any of `width`, `height` and `stride` may be null. Returns `false` on
// failure with `error` filled.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. Each out-pointer is null or
// writable. `error` is null or points to a writable `pdfrum_error`.
bool pdfrum_page_render_size(const pdfrum_page *page,
                             double scale,
                             uint32_t *width,
                             uint32_t *height,
                             uintptr_t *stride,
                             pdfrum_error *error);

// Every occurrence of `needle` in the page's text, as a list handle.
//
// `ignore_case` true is a case-insensitive search, which is the facade's own
// default. Each hit is a half-open character range into the same text
// [`pdfrum_page_text`] returns. Free the list with `pdfrum_hits_free`.
//
// An empty needle yields an empty list rather than a hit at every position.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `needle` is a non-null
// NUL-terminated UTF-8 string. `error` is null or points to a writable
// `pdfrum_error`.
pdfrum_hits *pdfrum_page_search(const pdfrum_page *page,
                                const char *needle,
                                bool ignore_case,
                                pdfrum_error *error);

// The page's size in PDF points, as the page's own boxes and rotation give it.
//
// `width` and `height` may each be null when the caller wants only the other.
// A null page is a no-op that leaves both untouched, which a caller who
// zeroed them first reads as zero.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `width` and `height` are
// each null or point to a writable `double`.
void pdfrum_page_size(const pdfrum_page *page, double *width, double *height);

// The page's text, in reading order, as a UTF-8 string.
//
// The caller owns the returned string and frees it with `pdfrum_free`.
// Returns null on failure with `error` filled; a page with no text yields an
// empty string, not null.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `error` is null or points
// to a writable `pdfrum_error`.
char *pdfrum_page_text(const pdfrum_page *page, pdfrum_error *error);

// The page's words, as a list handle.
//
// A handle rather than a caller-filled array on purpose: each word carries
// two strings, and a handle owns them all so there is **no per-word free**.
// Read the count with `pdfrum_words_count`, each word with
// `pdfrum_words_get`, and free the lot with `pdfrum_words_free`. Every
// `const char *` a word carries points into the handle and is invalid once
// the handle is freed.
//
// # Safety
//
// `page` is null or a live, unclosed page handle. `error` is null or points
// to a writable `pdfrum_error`.
pdfrum_words *pdfrum_page_words(const pdfrum_page *page, pdfrum_error *error);

// The library's version, as a static NUL-terminated string.
//
// The pointer is to static storage: it is valid for the life of the process,
// it is never freed, and it must **not** be passed to [`pdfrum_free`].
const char *pdfrum_version(void);

// How many words the list holds.
//
// Returns 0 for a null handle, which is also the answer for an empty list; a
// caller who must tell them apart checks the handle it was given.
//
// # Safety
//
// `list` is null or a live `pdfrum_words` that has not been freed.
uintptr_t pdfrum_words_count(const pdfrum_words *list);

// Frees the list and everything in it.
//
// One free for the whole list; there is no per-item free. A null pointer is a
// no-op.
//
// # Safety
//
// `list` is null or a live `pdfrum_words` that has not already been freed, and no
// other thread is using it.
void pdfrum_words_free(pdfrum_words *list);

// Copies one of the words into `out`.
//
// `index` is zero-based. Returns `false` — leaving `out` untouched — for a
// null handle, a null `out`, or an index at or past the count.
//
// Any `const char *` the item carries points **into the handle** and is
// invalid once the handle is freed. Copy it if it must outlive the list.
//
// # Safety
//
// `list` is null or a live `pdfrum_words` that has not been freed. `out` is null
// or points to a writable `pdfrum_word`.
bool pdfrum_words_get(const pdfrum_words *list,
                      uintptr_t index,
                      pdfrum_word *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
