[package]
name = "pdfrum-filters"
description = "PDF stream filters: Flate, LZW, RunLength, ASCIIHex/85, CCITT"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
pdfrum-common.workspace = true
pdfrum-object.workspace = true

hayro-ccitt.workspace = true
miniz_oxide.workspace = true
thiserror.workspace = true
weezl.workspace = true
