[package]
name = "pdfrum-text"
description = "Text extraction: reading order, search, link detection"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
pdfrum-common.workspace = true
pdfrum-object.workspace = true
pdfrum-font.workspace = true
pdfrum-page.workspace = true
kurbo.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
pdfrum-filters.workspace = true
pdfrum-parser.workspace = true
