[package]
name = "pdfrum-raster-tinyskia"
description = "tiny-skia implementation of pdfrum-render's RenderDevice"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["pdf", "render", "tiny-skia", "rasterizer"]
categories = ["graphics", "rendering"]

[lints]
workspace = true

[dependencies]
pdfrum-render.workspace = true
pdfrum-page.workspace = true
kurbo.workspace = true
peniko.workspace = true
tiny-skia.workspace = true
