//! JPEG 2000 decoding, behind the thin entry point SPEC.md §12 requires.
//!
//! # The colorspace override table
//!
//! A JPX image's colour space comes from **both** the PDF dictionary and the
//! codestream, and reconciling them is a table rather than a rule. The
//! interesting rows are the failures: a `/DeviceGray` image whose codestream
//! says RGB does not fall back to anything — **the whole load fails**. And a
//! three-component space whose codestream has four channels and says sRGB
//! takes the alpha-dropping path, a special case added for PDFs generated by
//! iOS.
//!
//! # `/SMaskInData`
//!
//! Only the value **1** is distinguished. It un-premultiplies the colour
//! against white and captures the alpha into a side buffer that becomes a
//! synthetic grayscale mask. Value 2, nominally "premultiplied", is *not*
//! distinguished and takes the same drop-alpha path as 0.

use crate::color::{ColorSpace, Family};
use crate::error::Error;
use pdfrum_common::Limits;

/// A decoded JPEG 2000 image.
#[derive(Debug, Clone, PartialEq)]
pub struct JpxImage {
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
    /// Components per pixel after the conversion action was applied.
    pub components: u8,
    /// Interleaved eight-bit samples, `width * height * components` bytes.
    pub data: Vec<u8>,
    /// The colour space the samples are in, when the conversion table
    /// replaced the dictionary's.
    pub space_override: Option<Option<ColorSpace>>,
    /// The alpha channel, when `/SMaskInData 1` captured one.
    pub alpha: Option<Vec<u8>>,
}

/// What the conversion table decided to do with the decoded channels.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JpxAction {
    /// Take one channel as grey.
    UseGray,
    /// Take three channels as RGB.
    UseRgb,
    /// Take four channels as CMYK.
    UseCmyk,
    /// Take the first three of four or more channels, dropping the rest.
    ConvertArgbToRgb,
    /// Take the channels as palette indices.
    UseIndexed,
    /// Leave the channels as they are.
    DoNothing,
    /// Refuse the image outright.
    Fail,
}

/// The codestream's own idea of its colour space, reduced to what the
/// conversion table asks about.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JpxColorSpace {
    /// Greyscale.
    Gray,
    /// sRGB.
    Srgb,
    /// CMYK.
    Cmyk,
    /// The codestream did not say, or said something unrecognised.
    Unspecified,
}

/// Whether a codestream space is the expected one, or simply unstated.
///
/// "Unspecified" counts as a match for every expectation, which is what lets
/// a raw codestream with no colour boxes be used at all.
fn matches_or_unspecified(actual: JpxColorSpace, expected: JpxColorSpace) -> bool {
    actual == expected || actual == JpxColorSpace::Unspecified
}

/// The conversion table from `docs/design/pdfrum-page.md` §1.19.7.
///
/// `space` is the PDF dictionary's colour space, `None` when it stated none.
#[must_use]
pub fn conversion_action(
    space: Option<&ColorSpace>,
    codestream: JpxColorSpace,
    channels: u8,
) -> JpxAction {
    let Some(space) = space else {
        // With no PDF colour space the codestream decides alone.
        return match codestream {
            JpxColorSpace::Unspecified => {
                if channels == 3 {
                    JpxAction::UseRgb
                } else {
                    JpxAction::DoNothing
                }
            }
            JpxColorSpace::Srgb => {
                if channels > 3 {
                    JpxAction::ConvertArgbToRgb
                } else {
                    JpxAction::UseRgb
                }
            }
            JpxColorSpace::Gray => JpxAction::UseGray,
            JpxColorSpace::Cmyk => JpxAction::UseCmyk,
        };
    };
    match space {
        ColorSpace::DeviceGray => {
            if matches_or_unspecified(codestream, JpxColorSpace::Gray) {
                JpxAction::UseGray
            } else {
                // No fallback: the whole load fails.
                JpxAction::Fail
            }
        }
        ColorSpace::DeviceRgb => {
            if !matches_or_unspecified(codestream, JpxColorSpace::Srgb) {
                JpxAction::Fail
            } else if channels > 3 {
                JpxAction::ConvertArgbToRgb
            } else {
                JpxAction::UseRgb
            }
        }
        ColorSpace::DeviceCmyk => {
            if matches_or_unspecified(codestream, JpxColorSpace::Cmyk) {
                JpxAction::UseCmyk
            } else {
                JpxAction::Fail
            }
        }
        ColorSpace::Indexed(_) if space.n_components() == 1 => JpxAction::UseIndexed,
        // The iOS special case: a three-component space whose codestream has
        // a fourth channel and claims sRGB drops the alpha.
        other
            if other.n_components() == 3 && channels == 4 && codestream == JpxColorSpace::Srgb =>
        {
            JpxAction::ConvertArgbToRgb
        }
        _ => JpxAction::DoNothing,
    }
}

impl JpxAction {
    /// The colour space this action installs, if it replaces the
    /// dictionary's.
    ///
    /// `Some(None)` means "reset to no colour space at all", which is what
    /// the RGB actions do: the samples are already device RGB, so keeping the
    /// original space would convert them twice.
    #[must_use]
    pub fn space_override(self) -> Option<Option<ColorSpace>> {
        match self {
            Self::UseGray => Some(Some(ColorSpace::DeviceGray)),
            Self::UseCmyk => Some(Some(ColorSpace::DeviceCmyk)),
            Self::UseRgb | Self::ConvertArgbToRgb => Some(None),
            Self::DoNothing | Self::UseIndexed | Self::Fail => None,
        }
    }

    /// How many components the samples carry after this action.
    #[must_use]
    pub fn components(self, channels: u8) -> u8 {
        match self {
            Self::UseGray | Self::UseIndexed => 1,
            Self::UseRgb | Self::ConvertArgbToRgb => 3,
            Self::UseCmyk => 4,
            Self::DoNothing => channels,
            Self::Fail => 0,
        }
    }
}

/// Decode a JPEG 2000 codestream or JP2 file.
///
/// `space` is the PDF dictionary's colour space, and `smask_in_data` its
/// `/SMaskInData`. `levels` is how many resolution levels to skip, which
/// halves the dimensions each time.
///
/// # Errors
///
/// [`Error::CodecRejected`] when the codestream will not decode or the
/// conversion table refuses the space combination, and
/// [`Error::ImageTooLarge`] when the result exceeds the byte budget.
pub fn decode_jpx(
    data: &[u8],
    space: Option<&ColorSpace>,
    smask_in_data: i64,
    levels: u8,
    limits: &Limits,
) -> Result<JpxImage, Error> {
    let settings = hayro_jpeg2000::DecodeSettings {
        // An `Indexed` PDF space wants the raw indices, not the palette's
        // colours: the palette lives in the PDF, not the codestream.
        resolve_palette_indices: !matches!(space, Some(ColorSpace::Indexed(_))),
        strict: false,
        target_resolution: None,
    };
    let image = hayro_jpeg2000::Image::new(data, &settings)
        .map_err(|_| Error::CodecRejected { codec: "JPX" })?;

    let codestream_space = match image.color_space() {
        hayro_jpeg2000::ColorSpace::Gray => JpxColorSpace::Gray,
        hayro_jpeg2000::ColorSpace::RGB => JpxColorSpace::Srgb,
        hayro_jpeg2000::ColorSpace::CMYK => JpxColorSpace::Cmyk,
        // An embedded ICC profile is deliberately discarded, so such an
        // image is treated as having said nothing.
        hayro_jpeg2000::ColorSpace::Icc { .. } | hayro_jpeg2000::ColorSpace::Unknown { .. } => {
            JpxColorSpace::Unspecified
        }
    };
    let channels = image.color_space().num_channels() + u8::from(image.has_alpha());

    let action = conversion_action(space, codestream_space, channels);
    if action == JpxAction::Fail {
        return Err(Error::CodecRejected { codec: "JPX" });
    }

    // A plain right shift, unlike the DCT path's ceiling division.
    let width = image.width() >> u32::from(levels);
    let height = image.height() >> u32::from(levels);
    if width == 0 || height == 0 {
        return Err(Error::CodecRejected { codec: "JPX" });
    }

    let mut context = hayro_jpeg2000::DecoderContext::default();
    let decoded = image
        .decode(&mut context)
        .map_err(|_| Error::CodecRejected { codec: "JPX" })?;
    let samples = decoded.data_u8();
    let source_channels = usize::from(channels).max(1);
    let out_components = action.components(channels);

    let pixels = usize::try_from(width)
        .ok()
        .and_then(|w| w.checked_mul(usize::try_from(height).ok()?))
        .ok_or(Error::ImageTooLarge)?;
    let out_len = pixels
        .checked_mul(usize::from(out_components).max(1))
        .ok_or(Error::ImageTooLarge)?;
    if out_len > limits.max_decoded_stream_len {
        return Err(Error::ImageTooLarge);
    }

    let mut out = vec![0u8; out_len];
    let mut alpha =
        (smask_in_data == 1 && action == JpxAction::ConvertArgbToRgb).then(|| vec![0u8; pixels]);
    let keep = usize::from(out_components).max(1);
    for i in 0..pixels {
        let src = i * source_channels;
        // `/SMaskInData 1` un-premultiplies against white; every other value,
        // including 2, simply drops the extra channel.
        let a = alpha
            .is_some()
            .then(|| samples.get(src + 3).copied().unwrap_or(255));
        for c in 0..keep {
            let v = samples.get(src + c).copied().unwrap_or(0);
            let v = match a {
                Some(a) => {
                    let na = u32::from(255 - a);
                    #[expect(
                        clippy::cast_possible_truncation,
                        reason = "the weighted average of two bytes stays within a byte"
                    )]
                    let blended = ((u32::from(v) * u32::from(a) + 255 * na) / 255) as u8;
                    blended
                }
                None => v,
            };
            if let Some(slot) = out.get_mut(i * keep + c) {
                *slot = v;
            }
        }
        if let (Some(buffer), Some(a)) = (alpha.as_mut(), a)
            && let Some(slot) = buffer.get_mut(i)
        {
            *slot = a;
        }
    }

    Ok(JpxImage {
        width,
        height,
        components: out_components,
        data: out,
        space_override: action.space_override(),
        alpha,
    })
}

/// Whether a colour space is one the JPX path treats as a stock device space.
#[must_use]
pub fn is_stock_device(space: &ColorSpace) -> bool {
    matches!(
        space.family(),
        Family::DeviceGray | Family::DeviceRgb | Family::DeviceCmyk
    )
}

#[cfg(test)]
mod tests {
    // Test fixtures quote the oracle's own vectors, compare floats exactly
    // where the behaviour being pinned is exact, and index arrays whose
    // length the fixture itself fixes.
    #![allow(
        clippy::unreadable_literal,
        clippy::float_cmp,
        clippy::indexing_slicing,
        clippy::cast_precision_loss,
        clippy::cast_possible_truncation,
        reason = "test fixtures quote oracle vectors verbatim and compare exactly"
    )]

    use super::{JpxAction, JpxColorSpace, conversion_action, decode_jpx, is_stock_device};
    use crate::color::{ColorSpace, Indexed};
    use pdfrum_common::Limits;

    #[test]
    fn device_gray_needs_a_grey_or_silent_codestream() {
        let gray = ColorSpace::DeviceGray;
        assert_eq!(
            conversion_action(Some(&gray), JpxColorSpace::Gray, 1),
            JpxAction::UseGray
        );
        assert_eq!(
            conversion_action(Some(&gray), JpxColorSpace::Unspecified, 1),
            JpxAction::UseGray
        );
        // An RGB codestream under a gray dictionary fails outright.
        assert_eq!(
            conversion_action(Some(&gray), JpxColorSpace::Srgb, 3),
            JpxAction::Fail
        );
    }

    #[test]
    fn device_rgb_drops_a_fourth_channel() {
        let rgb = ColorSpace::DeviceRgb;
        assert_eq!(
            conversion_action(Some(&rgb), JpxColorSpace::Srgb, 3),
            JpxAction::UseRgb
        );
        assert_eq!(
            conversion_action(Some(&rgb), JpxColorSpace::Srgb, 4),
            JpxAction::ConvertArgbToRgb
        );
        assert_eq!(
            conversion_action(Some(&rgb), JpxColorSpace::Cmyk, 4),
            JpxAction::Fail
        );
    }

    #[test]
    fn device_cmyk_needs_a_cmyk_or_silent_codestream() {
        let cmyk = ColorSpace::DeviceCmyk;
        assert_eq!(
            conversion_action(Some(&cmyk), JpxColorSpace::Cmyk, 4),
            JpxAction::UseCmyk
        );
        assert_eq!(
            conversion_action(Some(&cmyk), JpxColorSpace::Gray, 1),
            JpxAction::Fail
        );
    }

    #[test]
    fn an_indexed_space_takes_the_raw_indices() {
        let indexed = ColorSpace::Indexed(Box::new(Indexed {
            base: Box::new(ColorSpace::DeviceRgb),
            max_index: 3,
            lookup: Box::from(&[0u8; 12][..]),
            component_ranges: Box::from(&[(0.0f32, 1.0f32); 3][..]),
        }));
        assert_eq!(
            conversion_action(Some(&indexed), JpxColorSpace::Srgb, 1),
            JpxAction::UseIndexed
        );
    }

    #[test]
    fn the_ios_special_case_drops_alpha_for_any_three_component_space() {
        // A `CalRGB` space, four channels, sRGB codestream.
        let cal = ColorSpace::CalRgb(Box::new(crate::color::CalRgb {
            white_point: [0.9505, 1.0, 1.089],
            black_point: [0.0; 3],
            gamma: None,
            matrix: None,
        }));
        assert_eq!(
            conversion_action(Some(&cal), JpxColorSpace::Srgb, 4),
            JpxAction::ConvertArgbToRgb
        );
        // Three channels instead takes the do-nothing path.
        assert_eq!(
            conversion_action(Some(&cal), JpxColorSpace::Srgb, 3),
            JpxAction::DoNothing
        );
    }

    #[test]
    fn without_a_pdf_space_the_codestream_decides_alone() {
        assert_eq!(
            conversion_action(None, JpxColorSpace::Unspecified, 3),
            JpxAction::UseRgb
        );
        assert_eq!(
            conversion_action(None, JpxColorSpace::Unspecified, 2),
            JpxAction::DoNothing
        );
        assert_eq!(
            conversion_action(None, JpxColorSpace::Srgb, 4),
            JpxAction::ConvertArgbToRgb
        );
        assert_eq!(
            conversion_action(None, JpxColorSpace::Gray, 1),
            JpxAction::UseGray
        );
        assert_eq!(
            conversion_action(None, JpxColorSpace::Cmyk, 4),
            JpxAction::UseCmyk
        );
    }

    #[test]
    fn the_rgb_actions_reset_the_space_rather_than_replacing_it() {
        assert_eq!(JpxAction::UseRgb.space_override(), Some(None));
        assert_eq!(JpxAction::ConvertArgbToRgb.space_override(), Some(None));
        assert_eq!(
            JpxAction::UseGray.space_override(),
            Some(Some(ColorSpace::DeviceGray))
        );
        assert_eq!(JpxAction::UseIndexed.space_override(), None);
        assert_eq!(JpxAction::DoNothing.space_override(), None);
    }

    #[test]
    fn garbage_is_rejected_rather_than_panicked_on() {
        let limits = Limits::default();
        for data in [&b""[..], b"\x00\x00", b"not jpeg2000", &[0xFFu8; 32]] {
            assert!(decode_jpx(data, None, 0, 0, &limits).is_err());
        }
    }

    #[test]
    fn stock_device_spaces_are_recognised() {
        assert!(is_stock_device(&ColorSpace::DeviceGray));
        assert!(is_stock_device(&ColorSpace::DeviceCmyk));
        assert!(!is_stock_device(&ColorSpace::Pattern(Box::default())));
    }
}
