//! What writing a document back out costs.
//!
//! One criterion group, `save`, over the 44 documents in `benches/corpus`, ids
//! spelt `<class>/<stem>` so `benches/src/bin/ratchet.rs` can aggregate by
//! class. A full rewrite — every object serialized, the cross-reference table
//! rebuilt, every stream re-encoded — which is this crate's writer end to end.
//!
//! # To memory, not to a file
//!
//! Deliberately: a save benchmark that writes to disk measures the page cache on
//! the second iteration and the disk on the first, and neither is the writer.
//! What is measured here is object serialization, the cross-reference table and
//! the stream re-encoding.
//!
//! This is the most allocation-dominated group in the suite — hence its 5% band
//! against the render groups' 3–4%, which the internal working notes measured
//! rather than chose. It has no oracle column: `pdfium_test` has no
//! full-rewrite mode to compare against, so `save` is a ratchet-only group with
//! no M12 target on it.

use std::hint::black_box;
use std::time::Duration;

use criterion::{Criterion, criterion_main};
use pdfrum::{Document, SaveOptions};
use pdfrum_corpus::{CORPUS, bytes};

/// A full rewrite, to memory.
fn save(c: &mut Criterion) {
    let mut group = c.benchmark_group("save");
    let options = SaveOptions::default();
    for doc in CORPUS {
        let Ok(opened) = Document::from_bytes(bytes(doc.stem)) else {
            continue;
        };
        group.bench_function(format!("{}/{}", doc.class.name(), doc.stem), |b| {
            b.iter(|| {
                let mut out = Vec::new();
                black_box(opened.write_to(&mut out, &options).ok());
                black_box(out.len())
            });
        });
    }
    group.finish();
}

// `criterion_group!` generates a `pub fn` the `missing_docs` lint cannot see a
// doc comment for — the attribute would land inside the macro's expansion.
#[allow(missing_docs, reason = "the item is generated by criterion_group!")]
mod group {
    use super::{Criterion, Duration, save};
    use criterion::criterion_group;

    criterion_group! {
        name = benches;
        // The suite's shared settings; the internal working notes has the
        // measurement behind them.
        config = Criterion::default()
            .measurement_time(Duration::from_secs(5))
            .warm_up_time(Duration::from_secs(2))
            .sample_size(50);
        targets = save
    }
}

criterion_main!(group::benches);
