#!/usr/bin/env nu
# The public-API baseline: regenerate docs/api-baseline/, or gate the
# working tree's surface against what is committed there.
#
# **This is a gate.** `scripts/ci.nu` runs `./scripts/api-snapshot.nu check`
# after `cargo doc`. A drift is a red CI run. Review the printed diff and, if
# the change is intended, run `./scripts/api-snapshot.nu update` deliberately
# — a change to the baseline is a change to what `cargo add pdfrum` sees.
#
# Why it was held back. The files under docs/api-baseline/ were taken
# first, at 9b8f74b (the commit that added docs/design/idiomatic-api.md), so
# each idiomatic-API work package could measure its own blast radius against a
# surface that had not already moved under it. The script's original header
# forbade wiring that measurement into ci.nu: a drift check during the pass
# would have reddened every intentional break, and the pass would have spent
# its life re-blessing the file it was supposed to be changing. WP13 is the
# step that turns the same command into a gate, now that the surface is the
# one we mean to keep. That happened 2026-09-03.
#
# Usage:
#
#   ./scripts/api-snapshot.nu            # same as `diff`
#   ./scripts/api-snapshot.nu diff       # print the delta; exit 1 on drift
#   ./scripts/api-snapshot.nu check      # the CI gate: drift is a failure, and
#                                        # the comparison is proven live
#   ./scripts/api-snapshot.nu update     # regenerate the committed baseline
#   ./scripts/api-snapshot.nu list       # print the per-crate item counts
#
# Requires `cargo public-api` and a nightly toolchain, because the tool reads
# rustdoc's JSON output and that is nightly-only. Neither is a dependency of
# this workspace: `cargo public-api` is a `~/.cargo/bin` binary, it is NOT in
# DEPS.md, and it must never appear in a crate's Cargo.toml. Install with
#
#   cargo install cargo-public-api --locked
#
# See docs/api-baseline/README.md for what the files contain.
#
# The **C** surface is under the same discipline and a different script.
# `crates/pdfrum-capi/include/pdfrum.h` is generated by cbindgen and committed,
# and scripts/capi-header.nu gates it: a drift against the source fails, and so
# does a mismatch between the header's declarations and the library's exported
# symbols. It is separate from this file rather than a target in it because the
# measurement is different in kind — cbindgen and `nm`, not rustdoc JSON — and
# because the C header has no `cargo public-api` to ask. Both are run by
# scripts/ci.nu.

# Where the committed snapshots live, relative to the repo root.
const BASELINE = 'docs/api-baseline'

# The toolchain rustdoc JSON needs. Pinned to the channel, not a date: the
# output format is stable enough across nightlies that a date pin would cost
# more in churn than it buys in reproducibility, and README.md records the
# exact rustc that produced the committed files.
const TOOLCHAIN = 'nightly'

# `-sss` is `--omit blanket-impls,auto-trait-impls,auto-derived-impls`.
#
# Without it roughly half of every file is `impl<T, U> Into<U> for T`,
# `impl Send for ...` and derived `Clone`/`Debug`/`PartialEq` — noise that is
# identical for every type and tells a reviewer nothing about the surface.
# With it the file is the API a reader would write down by hand, which is what
# STYLE.md §4's "one screen a reviewer can read" is measured against.
#
# The trade: an auto-trait regression (a type quietly losing `Send`) does not
# show in the diff. The facade already has a unit test asserting `Send + Sync`
# on its public types — that is the check for that property, and it is a better
# one than a 400-line diff nobody reads.
const SIMPLIFY = '-sss'

# Every workspace member that publishes a library, and is therefore a surface
# some `cargo add` reaches.
#
# Read from the manifests rather than listed here, on the same reasoning as
# check-no-boa.nu: a crate added to the workspace should appear in the baseline
# without anyone remembering to edit this file. Two kinds of member are
# excluded, and both exclusions are recorded in the README so a reader does not
# have to infer them from a missing file:
#
#   - `publish = false` (pdfrum-raster-vello, pdfrum-script). Nothing can
#     `cargo add` them, so they have no public API in the sense this measures.
#     docs/design/idiomatic-api.md §4 rules that the *published* members stay
#     published; these two were never in that set.
#   - No library target (pdfrum-tool). A binary has no public API at all;
#     `cargo public-api` fails on it rather than emitting an empty file.
#
# `conformance/` and `benches/` are workspace members too, and are excluded for
# both reasons at once.
def published-libs []: nothing -> list<string> {
    glob crates/*/Cargo.toml
    | sort
    | each {|manifest|
        let m = (open $manifest)
        # `publish` absent means published; `publish = false` means not.
        let published = (($m.package.publish? | default true) != false)
        # A crate with src/lib.rs has a library target. Cargo's autodiscovery
        # makes this exact for every crate in this workspace; a manifest that
        # named a `[lib] path` elsewhere would need reading, and none does.
        let has_lib = (($manifest | path dirname | path join src lib.rs) | path exists)
        if $published and $has_lib { $m.package.name } else { null }
    }
    | compact
}

# The non-default surfaces worth recording, as `{file, crate, features}`.
#
# The baseline is a *default*-features measurement, because the default surface
# is what `cargo add <crate>` gets and that is the surface WP13 will gate. One
# feature earns a second file anyway, and the test is whether the crate's own
# documentation tells an embedder to turn it on:
#
#   - `pdfrum --features javascript` (WP12) does. The facade's crate docs carry a
#     `# Features` section naming it, and it adds seven types and two
#     constructors an embedder is meant to use — a surface no file would record
#     otherwise, so a change to it would be invisible to every gate here.
#   - `pdfrum --features svg` does. It puts `to_svg`/`to_svg_on` on the
#     facade's page types and a `svg` module beside them — the whole point of
#     the feature is that surface, and no other file records it.
#   - `pdfrum-render/profiling` does not. It is a profiling switch, not a
#     surface offered to callers.
#   - `pdfrum-form/javascript` does, but its items are the same ones
#     `pdfrum+javascript.txt` records one layer up, and the facade is the surface a
#     `cargo add` reaches. Recording it twice would make one API change diff in
#     two files.
#
# Named here rather than derived, on purpose: a feature entering this list is a
# statement that its surface is part of the product, and that should be a
# decision someone makes rather than a consequence of a manifest edit.
const FEATURED = [
    {file: 'pdfrum+javascript', crate: 'pdfrum', features: 'javascript'}
    {file: 'pdfrum+png', crate: 'pdfrum', features: 'png'}
    {file: 'pdfrum+markdown', crate: 'pdfrum', features: 'markdown'}
    {file: 'pdfrum+svg', crate: 'pdfrum', features: 'svg'}
    {file: 'pdfrum+tinyskia+agg', crate: 'pdfrum', features: 'tinyskia,agg'}
    {file: 'pdfrum-page+codecs', crate: 'pdfrum-page', features: 'jpx,jbig2,ccitt'}
    {file: 'pdfrum-filters+ccitt', crate: 'pdfrum-filters', features: 'ccitt'}
    {file: 'pdfrum-font+system-fonts', crate: 'pdfrum-font', features: 'system-fonts'}
    {file: 'pdfrum-render+png', crate: 'pdfrum-render', features: 'png'}
]

# One crate's public API, as `cargo public-api` prints it.
#
# A failure here is fatal rather than an empty file. The whole point of a
# baseline is that a missing surface is loud: a crate that stopped building
# would otherwise diff as "every public item removed", which reads as a
# spectacular API break rather than as a broken build.
def surface [crate: string, features: string = '']: nothing -> string {
    let flags = (if ($features | is-empty) { [] } else { [--features $features] })
    let r = (^cargo $"+($TOOLCHAIN)" public-api $SIMPLIFY -p $crate ...$flags | complete)
    if $r.exit_code != 0 {
        print --stderr $"error: `cargo public-api -p ($crate)` failed:"
        $r.stderr | lines | each {|l| print --stderr $"  ($l)" } | ignore
        print --stderr ""
        print --stderr $"       This is fatal: a crate that will not build has no"
        print --stderr $"       measurable surface, and writing an empty file would"
        print --stderr $"       diff as though every public item had been removed."
        exit 1
    }
    $r.stdout
}

def require-tool []: nothing -> nothing {
    if (which cargo-public-api | is-empty) {
        print --stderr "error: cargo-public-api is not installed."
        print --stderr "       install with: cargo install cargo-public-api --locked"
        print --stderr "       It is developer tooling only — do not add it to DEPS.md"
        print --stderr "       or to any crate's Cargo.toml."
        exit 1
    }
    let toolchains = (^rustup toolchain list | lines)
    if ($toolchains | where {|t| $t | str starts-with $TOOLCHAIN } | is-empty) {
        print --stderr $"error: the ($TOOLCHAIN) toolchain is not installed, and rustdoc"
        print --stderr $"       JSON — which cargo-public-api reads — is nightly-only."
        print --stderr $"       install with: rustup toolchain install ($TOOLCHAIN)"
        exit 1
    }
}

# Regenerate every committed snapshot.
def "main update" [] {
    cd ($env.FILE_PWD | path dirname)
    require-tool
    mkdir $BASELINE

    let crates = (published-libs)
    print $"==> regenerating the API baseline for ($crates | length) published library crates"
    for crate in $crates {
        let path = ($BASELINE | path join $"($crate).txt")
        surface $crate | save --force $path
        print $"  ($crate)"
    }
    for extra in $FEATURED {
        let path = ($BASELINE | path join $"($extra.file).txt")
        surface $extra.crate $extra.features | save --force $path
        print $"  ($extra.file)"
    }
    let total = (($crates | length) + ($FEATURED | length))
    print ""
    print $"Wrote ($total) files to ($BASELINE)/."
    print "Review the diff before committing: this is a baseline, and a change to"
    print "it is a change to what `cargo add pdfrum` sees."
}

# Set difference both ways. `cargo public-api` emits its items in a stable
# sort, so a plain line-set comparison is exactly the API delta — no
# reordering noise to filter out, which is why this can be structured data
# rather than a shell out to `diff`.
def line-delta [now: list<string>, then: list<string>]: nothing -> record {
    {
        added: ($now | where {|l| $l not-in $then })
        removed: ($then | where {|l| $l not-in $now })
    }
}

# One crate's committed snapshot vs the working tree, as structured data.
def snapshot-delta [target: record]: nothing -> record {
    let path = ($BASELINE | path join $"($target.file).txt")
    let now = (surface $target.crate $target.features | lines)
    let then = (if ($path | path exists) { open --raw $path | lines } else { [] })
    (line-delta $now $then) | merge {
        crate: $target.file
        now: $now
        then: $then
        missing_baseline: (not ($path | path exists))
    }
}

def snapshot-targets []: nothing -> list<record> {
    (
        (published-libs | each {|crate| {file: $crate, crate: $crate, features: ''} })
        ++ $FEATURED
    )
}

def print-delta [r: record] {
    print ""
    if $r.missing_baseline {
        print $"($r.crate): no committed baseline — new crate?"
    } else {
        print $"($r.crate): +($r.added | length) -($r.removed | length)"
    }
    $r.removed | each {|l| print $"  - ($l)" } | ignore
    $r.added   | each {|l| print $"  + ($l)" } | ignore
}

# Diff the working tree's surface against the committed baseline.
#
# Exits non-zero when they differ. `check` is the CI spelling of the same
# comparison, with the failure message a developer acting on a red gate needs.
def "main diff" [] {
    cd ($env.FILE_PWD | path dirname)
    require-tool

    let targets = (snapshot-targets)
    print $"==> diffing ($targets | length) surfaces against the committed baseline"

    # Collected rather than printed as they go, so the summary can lead with
    # the count and a reader knows how much scrolling is ahead of them.
    let results = ($targets | each {|target| snapshot-delta $target })
    let changed = ($results | where {|r| ($r.added | is-not-empty) or ($r.removed | is-not-empty) })

    for r in $changed { print-delta $r }

    print ""
    if ($changed | is-empty) {
        print "The public API matches the committed baseline."
        return
    }
    print $"($changed | length) of ($targets | length) surfaces differ from the baseline."
    print "Review the diff. A change to the baseline is a change to what"
    print "`cargo add pdfrum` sees. If this is intended, re-record it with"
    print "  ./scripts/api-snapshot.nu update"
    print "deliberately, and say in the commit message why the surface moved."
    exit 1
}

# The CI gate. Same comparison as `diff`, then a non-vacuity proof that the
# set-difference still reports a planted extra item — so a comparison that
# stopped looking cannot pass by matching an empty delta.
def "main check" [] {
    cd ($env.FILE_PWD | path dirname)
    require-tool

    let targets = (snapshot-targets)
    print $"==> public-API snapshot: ($targets | length) surfaces must match the baseline"

    let results = ($targets | each {|target| snapshot-delta $target })
    let changed = ($results | where {|r| ($r.added | is-not-empty) or ($r.removed | is-not-empty) })

    for r in $changed { print-delta $r }

    if not ($changed | is-empty) {
        print ""
        print --stderr $"error: ($changed | length) of ($targets | length) surfaces differ from the committed baseline."
        print --stderr "       Review the diff above. A change to docs/api-baseline/"
        print --stderr "       is a change to what `cargo add pdfrum` sees. If this is"
        print --stderr "       intended, re-record it deliberately with"
        print --stderr "         ./scripts/api-snapshot.nu update"
        exit 1
    }
    print "ok: the public API matches the committed baseline"

    # The converse, so the check cannot pass by having stopped looking.
    # A phantom item in the committed set must show up as a removal against
    # the working tree we just measured — one cargo-public-api run, not two.
    print "==> the snapshot comparison does still see a planted item"
    let probe = 'pub fn pdfrum::planted_wp13_probe()'
    let planted = ($results | each {|r|
        (line-delta $r.now ($r.then | append $probe)).removed
    } | flatten)
    if $probe not-in $planted {
        print --stderr "error: a planted public item was not reported as drift —"
        print --stderr "       the comparison above is measuring nothing."
        exit 1
    }
    print "ok: a planted public item is reported as drift"

    print ""
    print "public-API snapshot: green."
}

# The per-crate item counts, as a table.
#
# This is the number STYLE.md §4's "fits in one lib.rs re-export block a
# reviewer can read in one screen" is actually about, and the reason it is here
# rather than in a comment somewhere: the claim is checkable, and WP11 is
# graded against it crate by crate.
def "main list" [] {
    cd ($env.FILE_PWD | path dirname)

    published-libs | each {|crate|
        let path = ($BASELINE | path join $"($crate).txt")
        if not ($path | path exists) { return null }
        let lines = (open --raw $path | lines)
        {
            crate: $crate
            items: ($lines | length)
            # `pub mod` is the WP11 tell: a curated crate re-exports types and
            # keeps its modules private, so every `pub mod` past the crate root
            # is a module tree a reviewer has to read instead of a name.
            'pub mod': ($lines | where {|l| $l | str starts-with 'pub mod ' } | length)
            'pub use': ($lines | where {|l| $l | str starts-with 'pub use ' } | length)
        }
    } | compact
}

def main [] {
    main diff
}
