#!/usr/bin/env nu
# The C header under the same discipline as the Rust API baseline.
#
# `crates/pdfrum-capi/include/pdfrum.h` is generated by `cbindgen` from the
# Rust signatures and **committed**. That pair is the whole point: generation
# means the header cannot drift from the library, and committing means a change
# to it is a diff a reviewer reads rather than a file that appears at build
# time. This script is what keeps both halves true.
#
# Two checks, and they fail for different reasons:
#
#   1. **Drift.** Regenerate the header into a temporary file and diff it
#      against the committed one. A difference means someone changed a Rust
#      signature or a doc comment without regenerating — the header in the tree
#      is no longer what the source says.
#   2. **Symbols.** `nm -D` the built `libpdfrum.so` and compare its exported
#      `pdfrum_*` functions against the ones the header declares. A symbol
#      without a declaration is a function no C caller can reach; a declaration
#      without a symbol is a link error waiting for the first caller. The drift
#      check alone catches neither, because both halves of *that* comparison
#      come from the same source file.
#
# `scripts/ci.nu` runs `check`. Regenerate deliberately with `update`, and say
# in the commit message why the C surface moved — a change here is a change to
# what a C program compiled against this library sees.
#
# Requires `cbindgen`, which is a `~/.cargo/bin` binary and is NOT's
# dependency tables (it has its own tools section there). Install with
#
#   cargo install cbindgen --locked

# Where the crate, its config and its committed header live.
const CRATE = 'crates/pdfrum-capi'
const HEADER = 'crates/pdfrum-capi/include/pdfrum.h'

# `pdfrum_page_markdown` exists only in a build with the `markdown` feature.
# The header declares it under `#if defined(PDFRUM_MARKDOWN)`, so one header
# serves both builds — which means the symbol comparison must know that a
# default build is *expected* not to export it. Listed here rather than
# derived: a second feature-guarded function should be a decision someone makes
# in this file, not a name that quietly joins a pattern.
const FEATURE_GUARDED = [pdfrum_page_markdown]

def require-tool []: nothing -> nothing {
    if (which cbindgen | is-empty) {
        print --stderr "error: cbindgen is not installed."
        print --stderr "       install with: cargo install cbindgen --locked"
        print --stderr "       It is developer tooling only — do not add it to a"
        print --stderr "       crate's Cargo.toml. See CONTRIBUTING.md."
        exit 1
    }
}

# The header cbindgen produces from the tree as it stands right now.
def generate [out: string]: nothing -> nothing {
    let r = (^cbindgen --config $"($CRATE)/cbindgen.toml" --crate pdfrum-capi --output $out
        | complete)
    if $r.exit_code != 0 {
        print --stderr "error: cbindgen failed:"
        $r.stderr | lines | each {|l| print --stderr $"  ($l)" } | ignore
        exit 1
    }
}

# Every `pdfrum_*` function the header declares.
#
# A declaration is a `name(` at the start of a parameter list. Comments mention
# these names constantly, so the match is anchored to the shape of a call
# rather than to the name alone: `pdfrum_free(void *ptr);` counts and
# "fails with `PDFRUM_CODE_LIMIT`" does not.
def declared []: nothing -> list<string> {
    open --raw $HEADER
    | lines
    | where {|l| not ($l | str trim | str starts-with '//') }
    | where {|l| not ($l | str trim | str starts-with '*') }
    | parse --regex '(?<name>\bpdfrum_[a-z0-9_]+)\s*\('
    | get name
    | uniq
    | sort
}

# Every `pdfrum_*` function the built library exports.
def exported [lib: string]: nothing -> list<string> {
    ^nm -D --defined-only $lib
    | lines
    | parse --regex '^\S+\s+T\s+(?<name>pdfrum_[a-z0-9_]+)$'
    | get name
    | uniq
    | sort
}

# The release cdylib, or a message saying how to build it.
#
# Two names, because a plain `cargo build` names the artefact after the lib
# target (`pdfrum_capi`, which has to differ from the facade's `pdfrum` or the
# workspace's docs and doctests collide) while `cargo cinstall` ships it as
# `libpdfrum.so`. Either is the same library and exports the same symbols.
def library []: nothing -> string {
    let target = ($env.CARGO_TARGET_DIR? | default 'target')
    let candidates = [
        ($target | path join release libpdfrum.so)
        ($target | path join release libpdfrum_capi.so)
    ]
    let found = ($candidates | where {|p| $p | path exists })
    if ($found | is-empty) {
        print --stderr "error: no built libpdfrum shared library. Looked for:"
        $candidates | each {|p| print --stderr $"  ($p)" } | ignore
        print --stderr "       build it with: cargo build -p pdfrum-capi --release"
        exit 1
    }
    $found | first
}

# Regenerate the committed header.
def "main update" [] {
    cd ($env.FILE_PWD | path dirname)
    require-tool
    generate $HEADER
    let count = (declared | length)
    print $"Wrote ($HEADER) — ($count) declared functions."
    print "Review the diff before committing: a change here is a change to what"
    print "a C program compiled against libpdfrum sees."
}

# The CI gate: the committed header matches the source, and the header matches
# the library.
def "main check" [] {
    cd ($env.FILE_PWD | path dirname)
    require-tool

    print "==> the committed C header matches the Rust source"
    let fresh = (mktemp --tmpdir --suffix .h pdfrum-header-XXXXXX)
    generate $fresh
    let committed = (open --raw $HEADER)
    let regenerated = (open --raw $fresh)
    if $committed != $regenerated {
        # `diff` is external and may be absent; the line delta below always
        # works and says enough to act on.
        let a = ($committed | lines)
        let b = ($regenerated | lines)
        print --stderr $"error: ($HEADER) differs from a fresh generation."
        for line in ($a | where {|l| $l not-in $b }) { print --stderr $"  - ($line)" }
        for line in ($b | where {|l| $l not-in $a }) { print --stderr $"  + ($line)" }
        print --stderr ""
        print --stderr "       The header is generated from the Rust signatures and"
        print --stderr "       committed. Someone changed a signature or a doc comment"
        print --stderr "       without regenerating. If the change is intended, run"
        print --stderr "         ./scripts/capi-header.nu update"
        print --stderr "       and commit the header alongside the source."
        rm --force $fresh
        exit 1
    }
    rm --force $fresh
    let names = (declared)
    print $"ok: the header is what the source generates — ($names | length) functions"

    print "==> every declared function is an exported symbol, and the reverse"
    let lib = (library)
    let symbols = (exported $lib)

    # A declaration with no symbol: a C caller that uses it fails to link.
    # `FEATURE_GUARDED` names are exempt in this direction only — the header
    # declares them under an `#ifdef` that a default build does not define.
    let undefined = ($names
        | where {|n| $n not-in $symbols and $n not-in $FEATURE_GUARDED }
        | sort)
    # A symbol with no declaration: a function no C caller can reach, and one
    # the header's contracts say nothing about. Never exempt: a feature-guarded
    # function that IS built must still be declared.
    let undeclared = ($symbols | where {|s| $s not-in $names } | sort)

    if not ($undefined | is-empty) {
        print --stderr "error: declared in the header but not exported by the library:"
        $undefined | each {|n| print --stderr $"  ($n)" } | ignore
    }
    if not ($undeclared | is-empty) {
        print --stderr "error: exported by the library but not declared in the header:"
        $undeclared | each {|n| print --stderr $"  ($n)" } | ignore
    }
    if not (($undefined | is-empty) and ($undeclared | is-empty)) {
        print --stderr ""
        print --stderr "       The header and the library must agree exactly. A symbol"
        print --stderr "       with no declaration is unreachable from C; a declaration"
        print --stderr "       with no symbol is a link error the first caller finds."
        exit 1
    }
    let guarded = ($names | where {|n| $n in $FEATURE_GUARDED and $n not-in $symbols })
    print $"ok: ($symbols | length) exported symbols match the header's declarations"
    if not ($guarded | is-empty) {
        print $"    \(($guarded | str join ', ') declared under a feature guard this build does not set\)"
    }

    print ""
    print "C header: green."
}

def main [] {
    main check
}
