//! What the engine costs, per document and per page.
//!
//! Four groups, each over the same fixture set (`../fixtures`, see its
//! `PROVENANCE.md`):
//!
//! - **open** — `Document::open` on bytes already in memory, so the number is
//!   parse and cross-reference recovery rather than the filesystem.
//! - **render** — every page of a document at one pixel per point, each with
//!   its own caches. What a caller who renders one page pays.
//! - **render-session** — the same pages through one [`RenderSession`], which
//!   is the M8 reuse path. Read against `render` it is the answer to "what
//!   does sharing the caches buy".
//! - **text** — every page's text extracted, each page independent.
//!
//! Per-document rather than per-page groups, because the oracle's
//! `pdfium_test --render-repeats` also times a whole document and comparing
//! per-page averages against a whole-document time would be arithmetic
//! dressed up as measurement. `scripts/bench-oracle.sh` times the same files
//! the same way; `docs/status/M8.md` carries the comparison.

use std::hint::black_box;
use std::sync::Arc;
use std::time::Duration;

use criterion::{Criterion, criterion_main};
use pdfrum::{Document, RenderOptions, RenderSession};

/// The fixture set, by file stem. Kept in one place so every group measures
/// the same documents and the tables line up.
const FIXTURES: &[&str] = &[
    "bookmarks",
    "bug_650",
    "cropped_text",
    "embedded_images",
    "latin_extended",
    "many_rectangles",
];

/// Read one fixture's bytes.
///
/// Benchmarks are run from the crate root, so the path is relative to it.
fn bytes(stem: &str) -> Arc<[u8]> {
    let path = format!("fixtures/{stem}.pdf");
    match std::fs::read(&path) {
        Ok(bytes) => Arc::from(bytes),
        Err(err) => panic!("fixture {path} is missing: {err}"),
    }
}

/// Opening a document: header, cross-reference, trailer, catalog.
///
/// Pages are deliberately *not* touched — the engine parses them on demand,
/// and this measures what `open` itself costs.
fn open(c: &mut Criterion) {
    let mut group = c.benchmark_group("open");
    for stem in FIXTURES {
        let bytes = bytes(stem);
        group.bench_function(*stem, |b| {
            b.iter(|| {
                let doc = Document::from_bytes(Arc::clone(&bytes)).expect("open");
                black_box(doc.page_count())
            });
        });
    }
    group.finish();
}

/// Rendering every page of a document, each page with fresh caches.
fn render(c: &mut Criterion) {
    let mut group = c.benchmark_group("render");
    let options = RenderOptions::default();
    for stem in FIXTURES {
        let doc = Document::from_bytes(bytes(stem)).expect("open");
        group.bench_function(*stem, |b| {
            b.iter(|| {
                for page in doc.pages() {
                    black_box(page.render(&options).ok());
                }
            });
        });
    }
    group.finish();
}

/// Rendering every page of a document through one shared [`RenderSession`].
///
/// The same work as `render`, differing only in that the fonts, images and
/// glyph outlines survive from one page to the next.
fn render_session(c: &mut Criterion) {
    let mut group = c.benchmark_group("render-session");
    let options = RenderOptions::default();
    for stem in FIXTURES {
        let doc = Document::from_bytes(bytes(stem)).expect("open");
        group.bench_function(*stem, |b| {
            b.iter(|| {
                let mut session = RenderSession::new();
                for page in doc.pages() {
                    black_box(page.render_session(&options, &mut session).ok());
                }
            });
        });
    }
    group.finish();
}

/// Extracting every page's text.
fn text(c: &mut Criterion) {
    let mut group = c.benchmark_group("text");
    for stem in FIXTURES {
        let doc = Document::from_bytes(bytes(stem)).expect("open");
        group.bench_function(*stem, |b| {
            b.iter(|| {
                for page in doc.pages() {
                    black_box(page.text().all_text().len());
                }
            });
        });
    }
    group.finish();
}

// `criterion_group!` generates a `pub fn` the `missing_docs` lint cannot see a
// doc comment for — the attribute would land inside the macro's expansion.
#[allow(missing_docs, reason = "the item is generated by criterion_group!")]
mod group {
    use super::{Criterion, Duration, open, render, render_session, text};
    use criterion::criterion_group;

    criterion_group! {
        name = benches;
        // Rendering a page is milliseconds, not nanoseconds, so the default
        // 3-second measurement window spends most of its time warming up.
        config = Criterion::default()
            .measurement_time(Duration::from_secs(5))
            .warm_up_time(Duration::from_secs(1));
        targets = open, render, render_session, text
    }
}

criterion_main!(group::benches);
