#!/usr/bin/env python3
"""Extract PDFium's static font data tables into Rust `const` source fragments.

The read-only C++ oracle checkout (`$PDFRUM_ORACLE_CHECKOUT`, default
`<repo>/../pdfium-c++`) holds a handful of hand-maintained lookup tables that
`pdfrum` needs verbatim: the
predefined simple-font encodings, the base-14 name/alias tables, the Japan1
vertical CID transforms, the substitution weight/skew ramps, and the GBK
Chinese font-name prefixes. This script reads them out of the C++ sources and
emits `.rs` fragments, so the port never transcribes a table by hand.

Usage:
    uv run crates/pdfrum-font/extract-tables.py [ORACLE_ROOT] [OUT_DIR]
"""

from __future__ import annotations

import os
import pathlib
import re
import sys

# ---------------------------------------------------------------- helpers


def read(oracle: pathlib.Path, rel: str) -> str:
    return (oracle / rel).read_text(encoding="utf-8", errors="surrogateescape")


def brace_body(src: str, anchor: str) -> str:
    """Return the text of the outermost brace-balanced initializer after `anchor`.

    `anchor` is a regex; the initializer is whatever follows its first match.
    """
    m = re.search(anchor, src)
    if m is None:
        raise ValueError(f"anchor {anchor!r} not found")
    start = src.index("{", m.end())
    depth = 0
    for j in range(start, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[start + 1 : j]
    raise ValueError(f"unbalanced braces after {anchor!r}")


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def wrap(items: list[str], indent: str = "    ", width: int = 96) -> str:
    """Join `items` into comma-separated lines under `width` columns."""
    lines: list[str] = []
    cur = indent
    for it in items:
        piece = it + ","
        if len(cur) + len(piece) + 1 > width and cur != indent:
            lines.append(cur.rstrip())
            cur = indent
        cur += piece + " "
    if cur.strip():
        lines.append(cur.rstrip())
    return "\n".join(lines)


HEADER = """\
// @generated by crates/pdfrum-font/extract-tables.py from the read-only PDFium C++ oracle
// checkout. Do not edit by hand; re-run the extractor instead.
//
// Source: {sources}
// License: PDFium, BSD 3-clause (LICENSE at the oracle checkout root).
// Original code copyright 2014 Foxit Software Inc.
"""

# ------------------------------------------------------- A) encodings

U16 = re.compile(r"0[xX][0-9a-fA-F]{1,4}\b")

# (rust name, C++ symbol, source file)
CODE_TABLES = [
    ("MS_SYMBOL_ENCODING", "kMSSymbolEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("STANDARD_ENCODING", "kStandardEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("MAC_ROMAN_ENCODING", "kMacRomanEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("ADOBE_WIN_ANSI_ENCODING", "kAdobeWinAnsiEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("MAC_EXPERT_ENCODING", "kMacExpertEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("ADOBE_SYMBOL_ENCODING", "kAdobeSymbolEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    ("ZAPF_ENCODING", "kZapfEncoding", "core/fpdfapi/font/cpdf_fontencoding.cpp"),
    # PDFDocEncoding's code table lives in the parser, not the font code.
    ("PDF_DOC_ENCODING", "kPDFDocEncoding", "core/fpdfapi/parser/fpdf_parser_decode.cpp"),
]

NAME_TABLES = [
    ("STANDARD_ENCODING_NAMES", "kStandardEncodingNames"),
    ("ADOBE_WIN_ANSI_ENCODING_NAMES", "kAdobeWinAnsiEncodingNames"),
    ("MAC_ROMAN_ENCODING_NAMES", "kMacRomanEncodingNames"),
    ("MAC_EXPERT_ENCODING_NAMES", "kMacExpertEncodingNames"),
    ("PDF_DOC_ENCODING_NAMES", "kPDFDocEncodingNames"),
    ("ADOBE_SYMBOL_ENCODING_NAMES", "kAdobeSymbolEncodingNames"),
    ("ZAPF_ENCODING_NAMES", "kZapfEncodingNames"),
]

# A C++ string literal or the `nullptr` keyword, in order.
NAME_TOK = re.compile(r'"((?:[^"\\]|\\.)*)"|\bnullptr\b')


def anchor_for(symbol: str) -> str:
    """Match `symbol = {`, `symbol[] = {` or `symbol[Size] = {`, across newlines."""
    return re.escape(symbol) + r"\s*(?:\[[^\]]*\])?\s*="


def extract_u16_table(src: str, symbol: str) -> list[int]:
    body = strip_comments(brace_body(src, anchor_for(symbol)))
    return [int(m.group(0), 16) for m in U16.finditer(body)]


def extract_name_table(src: str, symbol: str) -> list[str | None]:
    body = strip_comments(brace_body(src, anchor_for(symbol)))
    out: list[str | None] = []
    for m in NAME_TOK.finditer(body):
        out.append(None if m.group(1) is None else m.group(1))
    return out



# What each table's rustdoc says. The provenance is in the file header, so a
# table's own comment says what it is for a reader of the crate, not where it
# was transcribed from.
TABLE_DOCS = {
    "MS_SYMBOL_ENCODING": "The Microsoft symbol charmap `(3, 0)`: code → Unicode, into the\nprivate-use area.",
    "STANDARD_ENCODING": "Adobe standard encoding: code → Unicode. `0x0000` where the encoding\nleaves a code unassigned.",
    "MAC_ROMAN_ENCODING": "`/MacRomanEncoding`: code → Unicode. `0x0000` where the encoding leaves\na code unassigned.",
    "ADOBE_WIN_ANSI_ENCODING": "`/WinAnsiEncoding` — Windows code page 1252: code → Unicode.",
    "MAC_EXPERT_ENCODING": "`/MacExpertEncoding`: code → Unicode, mostly into the private-use area.",
    "ADOBE_SYMBOL_ENCODING": "The Symbol font's own character set: code → Unicode.",
    "ZAPF_ENCODING": "The ZapfDingbats font's own character set: code → Unicode.",
    "PDF_DOC_ENCODING": "`/PDFDocEncoding`: code → Unicode. Unlike the others it assigns codes\nbelow 32.",
    "STANDARD_ENCODING_NAMES": "Adobe standard encoding's glyph names, indexed from code 32.",
    "ADOBE_WIN_ANSI_ENCODING_NAMES": "`/WinAnsiEncoding`'s glyph names, indexed from code 32.",
    "MAC_ROMAN_ENCODING_NAMES": "`/MacRomanEncoding`'s glyph names, indexed from code 32.",
    "MAC_EXPERT_ENCODING_NAMES": "`/MacExpertEncoding`'s glyph names, indexed from code 32.",
    "PDF_DOC_ENCODING_NAMES": "`/PDFDocEncoding`'s glyph names, indexed from code **24**, not 32.",
    "ADOBE_SYMBOL_ENCODING_NAMES": "The Symbol font's glyph names, indexed from code 32.",
    "ZAPF_ENCODING_NAMES": "The ZapfDingbats font's glyph names, indexed from code 32.",
}


def rustdoc(rust: str) -> str:
    return "".join(f"/// {line}\n" for line in TABLE_DOCS[rust].split("\n"))

def emit_encodings(oracle: pathlib.Path, out: pathlib.Path, report: list[str]) -> None:
    srcs = {
        rel: read(oracle, rel)
        for rel in {rel for _, _, rel in CODE_TABLES}
    }
    fontenc = read(oracle, "core/fpdfapi/font/cpdf_fontencoding.cpp")

    chunks = [
        HEADER.format(
            sources="core/fpdfapi/font/cpdf_fontencoding.cpp, "
            "core/fpdfapi/parser/fpdf_parser_decode.cpp"
        )
    ]

    for rust, symbol, rel in CODE_TABLES:
        vals = extract_u16_table(srcs[rel], symbol)
        assert len(vals) == 256, f"{symbol}: {len(vals)} entries, expected 256"
        report.append(f"A code table {symbol:<24} -> {rust:<26} {len(vals)} entries")
        chunks.append(
            rustdoc(rust)
            + f"pub(crate) const {rust}: [u16; 256] = [\n"
            + wrap([f"0x{v:04x}" for v in vals])
            + "\n];\n"
        )

    for rust, symbol in NAME_TABLES:
        names = extract_name_table(fontenc, symbol)
        n = len(names)
        report.append(f"A name table {symbol:<28} -> {rust:<30} N = {n} "
                      f"({sum(x is None for x in names)} nullptr)")
        items = ["None" if x is None else f'Some("{x}")' for x in names]
        chunks.append(
            rustdoc(rust)
            + f"pub(crate) const {rust}: [Option<&str>; {n}] = [\n"
            + wrap(items)
            + "\n];\n"
        )

    (out / "encoding_tables.rs").write_text("\n".join(chunks))


# ------------------------------------------------- B) standard font tables

VARIANT = {
    "kCourier": "Courier",
    "kCourierBold": "CourierBold",
    "kCourierBoldOblique": "CourierBoldOblique",
    "kCourierOblique": "CourierOblique",
    "kHelvetica": "Helvetica",
    "kHelveticaBold": "HelveticaBold",
    "kHelveticaBoldOblique": "HelveticaBoldOblique",
    "kHelveticaOblique": "HelveticaOblique",
    "kTimes": "Times",
    "kTimesBold": "TimesBold",
    "kTimesBoldOblique": "TimesBoldOblique",
    "kTimesOblique": "TimesOblique",
    "kSymbol": "Symbol",
    "kDingbats": "Dingbats",
}

ALT_ENTRY = re.compile(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*CFX_StandardFont::(k\w+)\s*\}')


def emit_standard_font(oracle: pathlib.Path, out: pathlib.Path, report: list[str]) -> None:
    rel = "core/fxge/cfx_standardfont.cpp"
    src = read(oracle, rel)

    alt_body = strip_comments(brace_body(src, anchor_for("kAltFontNames")))
    entries = [(m.group(1), VARIANT[m.group(2)]) for m in ALT_ENTRY.finditer(alt_body)]
    report.append(f"B kAltFontNames                             {len(entries)} entries")

    base14 = extract_name_table(src, "kBase14FontNames")
    assert len(base14) == 14 and all(base14), "kBase14FontNames must be 14 non-null names"
    report.append(f"B kBase14FontNames                          {len(base14)} entries")

    lines = [HEADER.format(sources=rel)]
    lines.append(
        "/// `kBase14FontNames` — the canonical PostScript names, indexed by\n"
        "/// `StandardFont`'s discriminant.\n"
        "pub(crate) const BASE14_FONT_NAMES: [&str; 14] = [\n"
        + "\n".join(f'    "{n}",' for n in base14)
        + "\n];\n"
    )
    lines.append(
        "/// `kAltFontNames` — aliases accepted for a base-14 face. Sorted\n"
        "/// case-insensitively; PDFium binary-searches it with `FXSYS_stricmp`.\n"
        f"pub(crate) const ALT_FONT_NAMES: &[(&str, StandardFont)] = &[\n"
        + "\n".join(f'    ("{name}", StandardFont::{v}),' for name, v in entries)
        + "\n];\n"
    )
    (out / "standard_font_tables.rs").write_text("\n".join(lines))


# --------------------------------------------------- C) Japan1 transforms

CID_ENTRY = re.compile(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,"
                       r"\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}")


def emit_japan1(oracle: pathlib.Path, out: pathlib.Path, report: list[str]) -> None:
    rel = "core/fpdfapi/font/cpdf_cidfont.cpp"
    src = read(oracle, rel)
    body = strip_comments(brace_body(src, anchor_for("kJapan1VerticalCIDs")))
    rows = [tuple(int(g) for g in m.groups()) for m in CID_ENTRY.finditer(body)]
    n = len(rows)
    # NOTE: the table is 154 rows in this oracle revision, not the 150 older
    # PDFium releases carried. The emitted array length follows the source.
    report.append(f"C kJapan1VerticalCIDs                       {n} entries")
    assert all(rows[i][0] < rows[i + 1][0] for i in range(n - 1)), "cids must be sorted"

    lines = [HEADER.format(sources=rel)]
    lines.append(
        "/// `kJapan1VerticalCIDs` — per-CID vertical-writing glyph transforms for\n"
        "/// Adobe-Japan1. Sorted by `cid`; PDFium binary-searches it.\n"
        f"pub(crate) const JAPAN1_VERTICAL_CIDS: [CidTransform; {n}] = [\n"
        + "\n".join(
            f"    CidTransform {{ cid: {c}, a: {a}, b: {b}, c: {cc}, d: {d}, e: {e}, f: {f} }},"
            for (c, a, b, cc, d, e, f) in rows
        )
        + "\n];\n"
    )
    (out / "japan1_transforms.rs").write_text("\n".join(lines))


# ------------------------------------------------------- D) weight tables

INT = re.compile(r"-?\d+")


def emit_weights(oracle: pathlib.Path, out: pathlib.Path, report: list[str]) -> None:
    rel = "core/fxge/cfx_substfont.cpp"
    src = read(oracle, rel)

    def nums(symbol: str) -> list[int]:
        body = strip_comments(brace_body(src, re.escape(symbol) + r"\s*=\s*std::to_array"))
        return [int(m.group(0)) for m in INT.finditer(body)]

    tables = {
        "WEIGHT_POW": ("kWeightPow", 100, "u8"),
        "WEIGHT_POW_11": ("kWeightPow11", 100, "u8"),
        "WEIGHT_POW_SHIFT_JIS": ("kWeightPowShiftJis", 100, "u8"),
        "ANGLE_SKEW": ("kAngleSkew", 30, "i8"),
    }
    lines = [HEADER.format(sources=rel)]
    data: dict[str, list[int]] = {}
    for rust, (symbol, expect, ty) in tables.items():
        vals = nums(symbol)
        assert len(vals) == expect, f"{symbol}: {len(vals)} entries, expected {expect}"
        data[symbol] = vals
        report.append(f"D {symbol:<42} {len(vals)} entries ([{ty}; {expect}])")
        lines.append(
            f"/// `{symbol}` (`{rel}`).\n"
            f"pub(crate) const {rust}: [{ty}; {expect}] = [\n"
            + wrap([str(v) for v in vals])
            + "\n];\n"
        )
    (out / "weight_tables.rs").write_text("\n".join(lines))

    # Cross-check the brief's claim about kWeightPow11's non-monotonic dips.
    w11 = data["kWeightPow11"]
    claim = {52: 43, 59: 45, 63: 46}
    got = {i: w11[i] for i in claim}
    dips = [i for i in range(1, len(w11)) if w11[i] < w11[i - 1]]
    report.append(
        f"D kWeightPow11 claimed dips {claim} -> actual {got} "
        f"({'MATCHES' if got == claim else 'MISMATCH'}); "
        f"all descending indices: {dips}"
    )


# ------------------------------------------------------- E) Chinese names


def emit_chinese(oracle: pathlib.Path, out: pathlib.Path, report: list[str]) -> None:
    rel = "core/fpdfapi/font/cpdf_font.cpp"
    src = read(oracle, rel)
    body = strip_comments(brace_body(src, anchor_for("kChineseFontNames")))
    raw = [m.group(1) for m in NAME_TOK.finditer(body) if m.group(1) is not None]
    # Each literal is four \xNN escapes.
    blobs = [[int(b, 16) for b in re.findall(r"\\x([0-9a-fA-F]{2})", s)] for s in raw]
    assert len(blobs) == 5 and all(len(b) == 4 for b in blobs), blobs
    report.append(f"E kChineseFontNames                         {len(blobs)} entries x 4 bytes")

    lines = [HEADER.format(sources=rel)]
    lines.append(
        "/// `kChineseFontNames` — GBK-encoded names of the five Chinese faces\n"
        "/// PDFium re-routes to `CPDF_CIDFont` when no FontFile2 is present.\n"
        "/// (SongTi, KaiTi, HeiTi, FangSong, XinSong.)\n"
        "pub(crate) const CHINESE_FONT_NAMES: [[u8; 4]; 5] = [\n"
        + "\n".join(
            "    [" + ", ".join(f"0x{b:02x}" for b in blob) + "]," for blob in blobs
        )
        + "\n];\n"
    )
    (out / "chinese_names.rs").write_text("\n".join(lines))


# ------------------------------------------------------------- driver



def oracle_checkout(argv_index: int = 1) -> pathlib.Path:
    """The read-only C++ PDFium checkout.

    One place, three inputs, in order: an explicit argument, then
    `$PDFRUM_ORACLE_CHECKOUT`, then `<repo>/../pdfium-c++`.
    """
    if len(sys.argv) > argv_index:
        return pathlib.Path(sys.argv[argv_index])
    repo = pathlib.Path(__file__).resolve().parents[2]
    return pathlib.Path(os.environ.get("PDFRUM_ORACLE_CHECKOUT", repo.parent / "pdfium-c++"))


def main() -> int:
    oracle = oracle_checkout()
    out = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else ".").resolve()
    out.mkdir(parents=True, exist_ok=True)

    report: list[str] = []
    emit_encodings(oracle, out, report)
    emit_standard_font(oracle, out, report)
    emit_japan1(oracle, out, report)
    emit_weights(oracle, out, report)
    emit_chinese(oracle, out, report)
    print("\n".join(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
