[package]
name = "pdfrum-page"
description = "Content-stream interpreter, graphics state, colorspaces, shadings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["pdf", "content", "colorspace", "shading"]
categories = ["graphics", "parser-implementations", "multimedia::images"]

[lints]
workspace = true

[dependencies]
pdfrum-common.workspace = true
pdfrum-object.workspace = true
pdfrum-filters.workspace = true
pdfrum-font.workspace = true
kurbo.workspace = true
smallvec.workspace = true
thiserror.workspace = true
moxcms.workspace = true
zune-jpeg.workspace = true
hayro-jpeg2000.workspace = true
hayro-jbig2.workspace = true

[dev-dependencies]
pdfrum-parser.workspace = true
