//! What building a page graph costs, before anything is drawn.
//!
//! One criterion group, `build`, over the 44 documents in `benches/corpus`, ids
//! spelt `<class>/<stem>` so `benches/src/bin/ratchet.rs` can aggregate by
//! class. New in the M12 per-crate split, and it is the group that split was
//! most worth doing for.
//!
//! # What it isolates, and why that matters
//!
//! `docs/status/M12.md` §3.1 measured that the *engine* half of a render — the
//! content-stream walk and its interpretation, which is this crate — is 54–85%
//! of the elapsed time, and §3's whole P1 pass then optimized the rasterizer
//! half. That was not a mistake at the time (the rasterizer is where the
//! profile could name a function on a machine without `perf`), but it left the
//! larger half with no benchmark of its own: a `build` regression could only be
//! seen through a render number that also contains a rasterizer.
//!
//! This group is that benchmark. It runs the content stream through the lexer,
//! the operator interpreter and the graphics-state machine, resolves the
//! resource dictionary's fonts and colour spaces and decodes its images, and
//! produces the `PageObject` list — and then stops, without rasterizing a
//! pixel. `docs/status/M12.md` §7's outstanding `bumpalo` question is a question
//! about this number.
//!
//! # Fresh caches per iteration, deliberately
//!
//! `Page::objects` builds with a fresh `BuildContext`, which is the cold
//! convention `render-cold` uses and for the same reason: a build with a warm
//! font and image cache is measuring the cache, and the interesting quantity
//! here is what the walk costs. Unlike the render groups this one has no oracle
//! column to be comparable with — `pdfium_test` has no mode that builds a page
//! and stops — so there is no warm variant and no target, only a ratchet.

use std::hint::black_box;
use std::time::Duration;

use criterion::{Criterion, criterion_main};
use pdfrum::Document;
use pdfrum_corpus::{CORPUS, bytes};

/// How many samples one document's build is worth.
///
/// The same shape as the render groups' override and for the same reason —
/// criterion's floor is `sample_size` iterations regardless of the window — but
/// a shorter list, because a build without a rasterizer is cheaper than a render
/// on every document except the ones whose cost *is* the image decode. Those
/// three are exactly the ones named here.
fn samples_for(stem: &str) -> usize {
    match stem {
        "image_bug_718762" | "image_bug_583804" | "image_bug_898443" => 10,
        _ => 50,
    }
}

/// Building every page's object list.
fn build(c: &mut Criterion) {
    let mut group = c.benchmark_group("build");
    for doc in CORPUS {
        let Ok(opened) = Document::from_bytes(bytes(doc.stem)) else {
            continue;
        };
        group.sample_size(samples_for(doc.stem));
        group.bench_function(format!("{}/{}", doc.class.name(), doc.stem), |b| {
            b.iter(|| {
                for page in opened.pages() {
                    black_box(page.objects().objects.len());
                }
            });
        });
    }
    group.finish();
}

// `criterion_group!` generates a `pub fn` the `missing_docs` lint cannot see a
// doc comment for — the attribute would land inside the macro's expansion.
#[allow(missing_docs, reason = "the item is generated by criterion_group!")]
mod group {
    use super::{Criterion, Duration, build};
    use criterion::criterion_group;

    criterion_group! {
        name = benches;
        // The suite's shared settings; docs/status/M12.md §2 has the
        // measurement behind them.
        config = Criterion::default()
            .measurement_time(Duration::from_secs(5))
            .warm_up_time(Duration::from_secs(2))
            .sample_size(50);
        targets = build
    }
}

criterion_main!(group::benches);
