//! Page-graph cost, before anything is drawn. Ids `<class>/<stem>`.
//!
//! Lexer, interpreter, graphics state, fonts, colour spaces, images — then
//! stop. Fresh `BuildContext` per iteration. No oracle column: `pdfium_test`
//! has no "build and stop" mode.

use std::hint::black_box;
use std::time::Duration;

use criterion::{Criterion, criterion_main};
use pdfrum::Document;
use pdfrum_corpus::{CORPUS, bytes};

/// Fewer samples on the three pathological image documents.
fn samples_for(stem: &str) -> usize {
    match stem {
        "image_bug_718762" | "image_bug_583804" | "image_bug_898443" => 10,
        _ => 50,
    }
}

/// Building every page's object list.
fn build(c: &mut Criterion) {
    let mut group = c.benchmark_group("build");
    for doc in CORPUS {
        let Ok(opened) = Document::from_bytes(bytes(doc.stem)) else {
            continue;
        };
        group.sample_size(samples_for(doc.stem));
        group.bench_function(format!("{}/{}", doc.class.name(), doc.stem), |b| {
            b.iter(|| {
                for page in opened.pages() {
                    black_box(page.objects().objects.len());
                }
            });
        });
    }
    group.finish();
}

// `criterion_group!` generates a `pub fn` the `missing_docs` lint cannot see a
// doc comment for — the attribute would land inside the macro's expansion.
#[allow(missing_docs, reason = "the item is generated by criterion_group!")]
mod group {
    use super::{Criterion, Duration, build};
    use criterion::criterion_group;

    criterion_group! {
        name = benches;
        // measurement behind them.
        config = Criterion::default()
            .measurement_time(Duration::from_secs(5))
            .warm_up_time(Duration::from_secs(2))
            .sample_size(50);
        targets = build
    }
}

criterion_main!(group::benches);
